// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminAnalyticsQuestion = `-- name: GetAdminAnalyticsQuestion :one
SELECT q.id, q.current_revision_id, current_revision.revision_number
FROM question q
JOIN question_revision current_revision
  ON current_revision.id = q.current_revision_id
WHERE q.id = $1
`

type GetAdminAnalyticsQuestionRow struct {
	ID                pgtype.UUID `json:"id"`
	CurrentRevisionID pgtype.UUID `json:"current_revision_id"`
	RevisionNumber    int32       `json:"revision_number"`
}

func (q *Queries) GetAdminAnalyticsQuestion(ctx context.Context, id pgtype.UUID) (GetAdminAnalyticsQuestionRow, error) {
	row := q.db.QueryRow(ctx, getAdminAnalyticsQuestion, id)
	var i GetAdminAnalyticsQuestionRow
	err := row.Scan(&i.ID, &i.CurrentRevisionID, &i.RevisionNumber)
	return i, err
}

const getAdminAnalyticsRevision = `-- name: GetAdminAnalyticsRevision :one
SELECT id, revision_number
FROM question_revision
WHERE question_id = $1 AND id = $2
`

type GetAdminAnalyticsRevisionParams struct {
	QuestionID pgtype.UUID `json:"question_id"`
	ID         pgtype.UUID `json:"id"`
}

type GetAdminAnalyticsRevisionRow struct {
	ID             pgtype.UUID `json:"id"`
	RevisionNumber int32       `json:"revision_number"`
}

func (q *Queries) GetAdminAnalyticsRevision(ctx context.Context, arg GetAdminAnalyticsRevisionParams) (GetAdminAnalyticsRevisionRow, error) {
	row := q.db.QueryRow(ctx, getAdminAnalyticsRevision, arg.QuestionID, arg.ID)
	var i GetAdminAnalyticsRevisionRow
	err := row.Scan(&i.ID, &i.RevisionNumber)
	return i, err
}

const getAdminPrivateQuestionAnalytics = `-- name: GetAdminPrivateQuestionAnalytics :one
SELECT
    count(*) FILTER (WHERE c.state IN ('unresolved', 'asked', 'skipped'))::bigint AS valid_offers,
    count(*) FILTER (WHERE c.state IN ('asked', 'skipped'))::bigint AS decisions,
    count(*) FILTER (WHERE c.state = 'asked')::bigint AS asked,
    count(*) FILTER (WHERE c.state = 'skipped')::bigint AS skipped,
    count(*) FILTER (WHERE c.state IN ('asked', 'skipped') AND c.liked_at IS NOT NULL)::bigint AS liked_decisions
FROM private_question_candidate c
JOIN private_conversation pc ON pc.id = c.conversation_id
WHERE c.question_id = $1
  AND ($2::uuid IS NULL OR c.question_revision_id = $2)
  AND c.state IN ('unresolved', 'asked', 'skipped')
HAVING count(DISTINCT pc.pair_id) >= $3::bigint
`

type GetAdminPrivateQuestionAnalyticsParams struct {
	QuestionID       pgtype.UUID `json:"question_id"`
	Column2          pgtype.UUID `json:"column_2"`
	MinDistinctPairs int64       `json:"min_distinct_pairs"`
}

type GetAdminPrivateQuestionAnalyticsRow struct {
	ValidOffers    int64 `json:"valid_offers"`
	Decisions      int64 `json:"decisions"`
	Asked          int64 `json:"asked"`
	Skipped        int64 `json:"skipped"`
	LikedDecisions int64 `json:"liked_decisions"`
}

func (q *Queries) GetAdminPrivateQuestionAnalytics(ctx context.Context, arg GetAdminPrivateQuestionAnalyticsParams) (GetAdminPrivateQuestionAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getAdminPrivateQuestionAnalytics, arg.QuestionID, arg.Column2, arg.MinDistinctPairs)
	var i GetAdminPrivateQuestionAnalyticsRow
	err := row.Scan(
		&i.ValidOffers,
		&i.Decisions,
		&i.Asked,
		&i.Skipped,
		&i.LikedDecisions,
	)
	return i, err
}

const getAdminQuestionCoverage = `-- name: GetAdminQuestionCoverage :many
SELECT
    qr.category,
    count(qr.id)::bigint AS eligible,
    count(qr.id) FILTER (WHERE qr.intensity = 'light')::bigint AS light,
    count(qr.id) FILTER (WHERE qr.intensity = 'medium')::bigint AS medium,
    count(qr.id) FILTER (WHERE qr.intensity = 'deep')::bigint AS deep
FROM question q
JOIN question_revision qr ON qr.id = q.current_revision_id
WHERE q.is_active
  AND qr.withdrawn_at IS NULL
  AND (qr.relationship_fit = 'both' OR qr.relationship_fit = $1::text)
  AND (qr.mode_fit = 'both' OR qr.mode_fit = $2::text)
GROUP BY qr.category
ORDER BY qr.category
`

type GetAdminQuestionCoverageParams struct {
	RelationshipType string `json:"relationship_type"`
	Mode             string `json:"mode"`
}

type GetAdminQuestionCoverageRow struct {
	Category string `json:"category"`
	Eligible int64  `json:"eligible"`
	Light    int64  `json:"light"`
	Medium   int64  `json:"medium"`
	Deep     int64  `json:"deep"`
}

func (q *Queries) GetAdminQuestionCoverage(ctx context.Context, arg GetAdminQuestionCoverageParams) ([]GetAdminQuestionCoverageRow, error) {
	rows, err := q.db.Query(ctx, getAdminQuestionCoverage, arg.RelationshipType, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminQuestionCoverageRow
	for rows.Next() {
		var i GetAdminQuestionCoverageRow
		if err := rows.Scan(
			&i.Category,
			&i.Eligible,
			&i.Light,
			&i.Medium,
			&i.Deep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminTogetherQuestionAnalytics = `-- name: GetAdminTogetherQuestionAnalytics :one
SELECT
    count(*)::bigint AS shown,
    count(*) FILTER (WHERE tsq.advanced_at IS NOT NULL)::bigint AS decisions,
    count(*) FILTER (WHERE tsq.advanced_at IS NOT NULL AND tsq.skipped_at IS NULL)::bigint AS continued,
    count(*) FILTER (WHERE tsq.advanced_at IS NOT NULL AND tsq.skipped_at IS NOT NULL)::bigint AS skipped,
    count(*) FILTER (WHERE tsq.advanced_at IS NOT NULL AND tsq.liked_at IS NOT NULL)::bigint AS liked_decisions
FROM together_session_question tsq
JOIN together_session ts ON ts.id = tsq.session_id
WHERE tsq.question_id = $1
  AND ($2::uuid IS NULL OR tsq.question_revision_id = $2)
HAVING count(DISTINCT ts.pair_id) >= $3::bigint
`

type GetAdminTogetherQuestionAnalyticsParams struct {
	QuestionID       pgtype.UUID `json:"question_id"`
	Column2          pgtype.UUID `json:"column_2"`
	MinDistinctPairs int64       `json:"min_distinct_pairs"`
}

type GetAdminTogetherQuestionAnalyticsRow struct {
	Shown          int64 `json:"shown"`
	Decisions      int64 `json:"decisions"`
	Continued      int64 `json:"continued"`
	Skipped        int64 `json:"skipped"`
	LikedDecisions int64 `json:"liked_decisions"`
}

func (q *Queries) GetAdminTogetherQuestionAnalytics(ctx context.Context, arg GetAdminTogetherQuestionAnalyticsParams) (GetAdminTogetherQuestionAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getAdminTogetherQuestionAnalytics, arg.QuestionID, arg.Column2, arg.MinDistinctPairs)
	var i GetAdminTogetherQuestionAnalyticsRow
	err := row.Scan(
		&i.Shown,
		&i.Decisions,
		&i.Continued,
		&i.Skipped,
		&i.LikedDecisions,
	)
	return i, err
}
