// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_session (
    id, auth_user_id, token_hash, created_at, expires_at, last_used_at
)
VALUES ($1, $2, $3, $4, $5, $4)
RETURNING id, auth_user_id, token_hash, created_at, expires_at, last_used_at, revoked_at
`

type CreateAuthSessionParams struct {
	ID         pgtype.UUID        `json:"id"`
	AuthUserID pgtype.UUID        `json:"auth_user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.AuthUserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO auth_user (id, kind, created_at)
VALUES ($1, $2, $3)
RETURNING id, kind, created_at, disabled_at
`

type CreateAuthUserParams struct {
	ID        pgtype.UUID        `json:"id"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createAuthUser, arg.ID, arg.Kind, arg.CreatedAt)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :execrows
WITH expired AS (
    SELECT candidate.id
    FROM auth_session AS candidate
    WHERE candidate.expires_at <= $1 OR candidate.revoked_at IS NOT NULL
    ORDER BY candidate.expires_at ASC
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
DELETE FROM auth_session AS session
USING expired
WHERE session.id = expired.id
`

type DeleteExpiredAuthSessionsParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context, arg DeleteExpiredAuthSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthSessions, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthSessionActor = `-- name: GetAuthSessionActor :one
SELECT
    s.id AS session_id,
    u.id AS auth_user_id,
    u.kind,
    u.created_at AS user_created_at,
    s.created_at AS session_created_at,
    s.expires_at,
    s.last_used_at
FROM auth_session AS s
JOIN auth_user AS u ON u.id = s.auth_user_id
WHERE s.token_hash = $1
  AND s.expires_at > $2
  AND s.revoked_at IS NULL
  AND u.disabled_at IS NULL
`

type GetAuthSessionActorParams struct {
	TokenHash []byte             `json:"token_hash"`
	Now       pgtype.Timestamptz `json:"now"`
}

type GetAuthSessionActorRow struct {
	SessionID        pgtype.UUID        `json:"session_id"`
	AuthUserID       pgtype.UUID        `json:"auth_user_id"`
	Kind             string             `json:"kind"`
	UserCreatedAt    pgtype.Timestamptz `json:"user_created_at"`
	SessionCreatedAt pgtype.Timestamptz `json:"session_created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) GetAuthSessionActor(ctx context.Context, arg GetAuthSessionActorParams) (GetAuthSessionActorRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionActor, arg.TokenHash, arg.Now)
	var i GetAuthSessionActorRow
	err := row.Scan(
		&i.SessionID,
		&i.AuthUserID,
		&i.Kind,
		&i.UserCreatedAt,
		&i.SessionCreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const hasAuthSession = `-- name: HasAuthSession :one
SELECT EXISTS (
    SELECT 1 FROM auth_session WHERE token_hash = $1
)
`

func (q *Queries) HasAuthSession(ctx context.Context, tokenHash []byte) (bool, error) {
	row := q.db.QueryRow(ctx, hasAuthSession, tokenHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAuthSessionTokenHashes = `-- name: ListAuthSessionTokenHashes :many
SELECT token_hash
FROM auth_session
WHERE auth_user_id = $1
`

func (q *Queries) ListAuthSessionTokenHashes(ctx context.Context, authUserID pgtype.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listAuthSessionTokenHashes, authUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var token_hash []byte
		if err := rows.Scan(&token_hash); err != nil {
			return nil, err
		}
		items = append(items, token_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewAuthSession = `-- name: RenewAuthSession :one
UPDATE auth_session
SET expires_at = $2, last_used_at = $3
WHERE id = $1
  AND expires_at > $3
  AND revoked_at IS NULL
RETURNING expires_at
`

type RenewAuthSessionParams struct {
	ID         pgtype.UUID        `json:"id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) RenewAuthSession(ctx context.Context, arg RenewAuthSessionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, renewAuthSession, arg.ID, arg.ExpiresAt, arg.LastUsedAt)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const revokeAuthSession = `-- name: RevokeAuthSession :execrows
UPDATE auth_session
SET revoked_at = $2
WHERE token_hash = $1
  AND revoked_at IS NULL
`

type RevokeAuthSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSession, arg.TokenHash, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
