// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUser = `-- name: CreateAdminUser :exec
INSERT INTO admin_user (auth_user_id, created_at)
VALUES ($1, $2)
`

type CreateAdminUserParams struct {
	AuthUserID pgtype.UUID        `json:"auth_user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error {
	_, err := q.db.Exec(ctx, createAdminUser, arg.AuthUserID, arg.CreatedAt)
	return err
}

const createAuthCredential = `-- name: CreateAuthCredential :exec
INSERT INTO auth_credential (auth_user_id, email_normalized, password_hash, created_at, password_updated_at)
VALUES ($1, $2, $3, $4, $4)
`

type CreateAuthCredentialParams struct {
	AuthUserID      pgtype.UUID        `json:"auth_user_id"`
	EmailNormalized string             `json:"email_normalized"`
	PasswordHash    string             `json:"password_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthCredential(ctx context.Context, arg CreateAuthCredentialParams) error {
	_, err := q.db.Exec(ctx, createAuthCredential,
		arg.AuthUserID,
		arg.EmailNormalized,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_session (
    id, auth_user_id, token_hash, created_at, expires_at, last_used_at
)
VALUES ($1, $2, $3, $4, $5, $4)
RETURNING id, auth_user_id, token_hash, created_at, expires_at, last_used_at, revoked_at
`

type CreateAuthSessionParams struct {
	ID         pgtype.UUID        `json:"id"`
	AuthUserID pgtype.UUID        `json:"auth_user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.AuthUserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAuthSessionForEnabledAdminUser = `-- name: CreateAuthSessionForEnabledAdminUser :execrows
INSERT INTO auth_session (id, auth_user_id, token_hash, created_at, expires_at, last_used_at)
SELECT $1, u.id, $3, $4, $5, $4
FROM auth_user AS u
JOIN admin_user AS a ON a.auth_user_id = u.id
WHERE u.id = $2 AND u.kind = 'admin' AND u.disabled_at IS NULL
`

type CreateAuthSessionForEnabledAdminUserParams struct {
	ID        pgtype.UUID        `json:"id"`
	ID_2      pgtype.UUID        `json:"id_2"`
	TokenHash []byte             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthSessionForEnabledAdminUser(ctx context.Context, arg CreateAuthSessionForEnabledAdminUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, createAuthSessionForEnabledAdminUser,
		arg.ID,
		arg.ID_2,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAuthSessionForEnabledRegisteredUser = `-- name: CreateAuthSessionForEnabledRegisteredUser :execrows
INSERT INTO auth_session (id, auth_user_id, token_hash, created_at, expires_at, last_used_at)
SELECT $1, auth_user.id, $3, $4, $5, $4
FROM auth_user
WHERE auth_user.id = $2 AND kind = 'registered' AND disabled_at IS NULL
`

type CreateAuthSessionForEnabledRegisteredUserParams struct {
	ID        pgtype.UUID        `json:"id"`
	ID_2      pgtype.UUID        `json:"id_2"`
	TokenHash []byte             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthSessionForEnabledRegisteredUser(ctx context.Context, arg CreateAuthSessionForEnabledRegisteredUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, createAuthSessionForEnabledRegisteredUser,
		arg.ID,
		arg.ID_2,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO auth_user (id, kind, created_at)
VALUES ($1, $2, $3)
RETURNING id, kind, created_at, disabled_at
`

type CreateAuthUserParams struct {
	ID        pgtype.UUID        `json:"id"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createAuthUser, arg.ID, arg.Kind, arg.CreatedAt)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const createRegisteredAuthUser = `-- name: CreateRegisteredAuthUser :one
INSERT INTO auth_user (id, kind, created_at)
VALUES ($1, 'registered', $2)
RETURNING id, kind, created_at, disabled_at
`

type CreateRegisteredAuthUserParams struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRegisteredAuthUser(ctx context.Context, arg CreateRegisteredAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createRegisteredAuthUser, arg.ID, arg.CreatedAt)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :execrows
WITH expired AS (
    SELECT candidate.id
    FROM auth_session AS candidate
    WHERE candidate.expires_at <= $1 OR candidate.revoked_at IS NOT NULL
    ORDER BY candidate.expires_at ASC
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
DELETE FROM auth_session AS session
USING expired
WHERE session.id = expired.id
`

type DeleteExpiredAuthSessionsParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context, arg DeleteExpiredAuthSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthSessions, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldAuthRateLimits = `-- name: DeleteOldAuthRateLimits :execrows
WITH expired AS (
    SELECT scope, subject
    FROM auth_rate_limit
    WHERE window_started_at <= $1 - interval '1 day'
    ORDER BY window_started_at ASC
    LIMIT 500
    FOR UPDATE SKIP LOCKED
)
DELETE FROM auth_rate_limit AS limits
USING expired
WHERE limits.scope = expired.scope AND limits.subject = expired.subject
`

func (q *Queries) DeleteOldAuthRateLimits(ctx context.Context, dollar_1 interface{}) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldAuthRateLimits, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAdminCredentialByEmail = `-- name: GetAdminCredentialByEmail :one
SELECT u.id AS auth_user_id, u.kind, u.disabled_at, c.password_hash
FROM auth_credential AS c
JOIN auth_user AS u ON u.id = c.auth_user_id
JOIN admin_user AS a ON a.auth_user_id = u.id
WHERE c.email_normalized = $1
`

type GetAdminCredentialByEmailRow struct {
	AuthUserID   pgtype.UUID        `json:"auth_user_id"`
	Kind         string             `json:"kind"`
	DisabledAt   pgtype.Timestamptz `json:"disabled_at"`
	PasswordHash string             `json:"password_hash"`
}

func (q *Queries) GetAdminCredentialByEmail(ctx context.Context, emailNormalized string) (GetAdminCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAdminCredentialByEmail, emailNormalized)
	var i GetAdminCredentialByEmailRow
	err := row.Scan(
		&i.AuthUserID,
		&i.Kind,
		&i.DisabledAt,
		&i.PasswordHash,
	)
	return i, err
}

const getAuthSessionActor = `-- name: GetAuthSessionActor :one
SELECT
    s.id AS session_id,
    u.id AS auth_user_id,
    u.kind,
    u.created_at AS user_created_at,
    s.created_at AS session_created_at,
    s.expires_at,
    s.last_used_at
FROM auth_session AS s
JOIN auth_user AS u ON u.id = s.auth_user_id
WHERE s.token_hash = $1
  AND s.expires_at > $2
  AND s.revoked_at IS NULL
  AND u.disabled_at IS NULL
`

type GetAuthSessionActorParams struct {
	TokenHash []byte             `json:"token_hash"`
	Now       pgtype.Timestamptz `json:"now"`
}

type GetAuthSessionActorRow struct {
	SessionID        pgtype.UUID        `json:"session_id"`
	AuthUserID       pgtype.UUID        `json:"auth_user_id"`
	Kind             string             `json:"kind"`
	UserCreatedAt    pgtype.Timestamptz `json:"user_created_at"`
	SessionCreatedAt pgtype.Timestamptz `json:"session_created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) GetAuthSessionActor(ctx context.Context, arg GetAuthSessionActorParams) (GetAuthSessionActorRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionActor, arg.TokenHash, arg.Now)
	var i GetAuthSessionActorRow
	err := row.Scan(
		&i.SessionID,
		&i.AuthUserID,
		&i.Kind,
		&i.UserCreatedAt,
		&i.SessionCreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCredentialByEmail = `-- name: GetCredentialByEmail :one
SELECT u.id AS auth_user_id, u.kind, u.disabled_at, c.password_hash
FROM auth_credential AS c
JOIN auth_user AS u ON u.id = c.auth_user_id
WHERE c.email_normalized = $1
`

type GetCredentialByEmailRow struct {
	AuthUserID   pgtype.UUID        `json:"auth_user_id"`
	Kind         string             `json:"kind"`
	DisabledAt   pgtype.Timestamptz `json:"disabled_at"`
	PasswordHash string             `json:"password_hash"`
}

func (q *Queries) GetCredentialByEmail(ctx context.Context, emailNormalized string) (GetCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByEmail, emailNormalized)
	var i GetCredentialByEmailRow
	err := row.Scan(
		&i.AuthUserID,
		&i.Kind,
		&i.DisabledAt,
		&i.PasswordHash,
	)
	return i, err
}

const hasAdminUser = `-- name: HasAdminUser :one
SELECT EXISTS (SELECT 1 FROM admin_user WHERE auth_user_id = $1)
`

func (q *Queries) HasAdminUser(ctx context.Context, authUserID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasAdminUser, authUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasAuthSession = `-- name: HasAuthSession :one
SELECT EXISTS (
    SELECT 1 FROM auth_session WHERE token_hash = $1
)
`

func (q *Queries) HasAuthSession(ctx context.Context, tokenHash []byte) (bool, error) {
	row := q.db.QueryRow(ctx, hasAuthSession, tokenHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isAdminAuthUser = `-- name: IsAdminAuthUser :one
SELECT EXISTS (
    SELECT 1
    FROM auth_user AS u
    JOIN admin_user AS a ON a.auth_user_id = u.id
    WHERE u.id = $1 AND u.kind = 'admin' AND u.disabled_at IS NULL
)
`

func (q *Queries) IsAdminAuthUser(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAdminAuthUser, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAuthSessionTokenHashes = `-- name: ListAuthSessionTokenHashes :many
SELECT token_hash
FROM auth_session
WHERE auth_user_id = $1
`

func (q *Queries) ListAuthSessionTokenHashes(ctx context.Context, authUserID pgtype.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listAuthSessionTokenHashes, authUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var token_hash []byte
		if err := rows.Scan(&token_hash); err != nil {
			return nil, err
		}
		items = append(items, token_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdminBootstrapEmail = `-- name: LockAdminBootstrapEmail :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockAdminBootstrapEmail(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockAdminBootstrapEmail, hashtextextended)
	return err
}

const lockAdminByEmailForRecovery = `-- name: LockAdminByEmailForRecovery :one
SELECT u.id AS auth_user_id
FROM auth_credential AS c
JOIN auth_user AS u ON u.id = c.auth_user_id
JOIN admin_user AS a ON a.auth_user_id = u.id
WHERE c.email_normalized = $1 AND u.kind = 'admin'
FOR UPDATE OF u, c
`

func (q *Queries) LockAdminByEmailForRecovery(ctx context.Context, emailNormalized string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockAdminByEmailForRecovery, emailNormalized)
	var auth_user_id pgtype.UUID
	err := row.Scan(&auth_user_id)
	return auth_user_id, err
}

const lockAuthUserForUpgrade = `-- name: LockAuthUserForUpgrade :one
SELECT id, kind, created_at, disabled_at
FROM auth_user
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockAuthUserForUpgrade(ctx context.Context, id pgtype.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, lockAuthUserForUpgrade, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const renewAuthSession = `-- name: RenewAuthSession :one
UPDATE auth_session
SET expires_at = $2, last_used_at = $3
WHERE id = $1
  AND expires_at > $3
  AND revoked_at IS NULL
RETURNING expires_at
`

type RenewAuthSessionParams struct {
	ID         pgtype.UUID        `json:"id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) RenewAuthSession(ctx context.Context, arg RenewAuthSessionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, renewAuthSession, arg.ID, arg.ExpiresAt, arg.LastUsedAt)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const revokeAuthSession = `-- name: RevokeAuthSession :execrows
UPDATE auth_session
SET revoked_at = $2
WHERE token_hash = $1
  AND revoked_at IS NULL
`

type RevokeAuthSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSession, arg.TokenHash, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAuthSessionByTokenHash = `-- name: RevokeAuthSessionByTokenHash :execrows
UPDATE auth_session
SET revoked_at = $2
WHERE token_hash = $1 AND revoked_at IS NULL
`

type RevokeAuthSessionByTokenHashParams struct {
	TokenHash []byte             `json:"token_hash"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAuthSessionByTokenHash(ctx context.Context, arg RevokeAuthSessionByTokenHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSessionByTokenHash, arg.TokenHash, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAuthSessionsForUser = `-- name: RevokeAuthSessionsForUser :execrows
UPDATE auth_session
SET revoked_at = $2
WHERE auth_user_id = $1 AND revoked_at IS NULL AND expires_at > $2
`

type RevokeAuthSessionsForUserParams struct {
	AuthUserID pgtype.UUID        `json:"auth_user_id"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAuthSessionsForUser(ctx context.Context, arg RevokeAuthSessionsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSessionsForUser, arg.AuthUserID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAuthCredentialPasswordHash = `-- name: UpdateAuthCredentialPasswordHash :exec
UPDATE auth_credential
SET password_hash = $2, password_updated_at = $3
WHERE auth_user_id = $1
`

type UpdateAuthCredentialPasswordHashParams struct {
	AuthUserID        pgtype.UUID        `json:"auth_user_id"`
	PasswordHash      string             `json:"password_hash"`
	PasswordUpdatedAt pgtype.Timestamptz `json:"password_updated_at"`
}

func (q *Queries) UpdateAuthCredentialPasswordHash(ctx context.Context, arg UpdateAuthCredentialPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateAuthCredentialPasswordHash, arg.AuthUserID, arg.PasswordHash, arg.PasswordUpdatedAt)
	return err
}

const upgradeAnonymousAuthUser = `-- name: UpgradeAnonymousAuthUser :execrows
UPDATE auth_user
SET kind = 'registered'
WHERE id = $1 AND kind = 'anonymous' AND disabled_at IS NULL
`

func (q *Queries) UpgradeAnonymousAuthUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, upgradeAnonymousAuthUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAdminLoginRateLimit = `-- name: UpsertAdminLoginRateLimit :one
WITH db_clock AS MATERIALIZED (
    SELECT clock_timestamp() AS now
)
INSERT INTO auth_rate_limit (scope, subject, window_started_at, count)
SELECT 'admin_login_ip', $1, db_clock.now, 1
FROM db_clock
ON CONFLICT (scope, subject) DO UPDATE
SET count = CASE
        WHEN auth_rate_limit.window_started_at <= (SELECT now FROM db_clock) - interval '1 minute' THEN 1
        ELSE auth_rate_limit.count + 1
    END,
    window_started_at = CASE
        WHEN auth_rate_limit.window_started_at <= (SELECT now FROM db_clock) - interval '1 minute' THEN (SELECT now FROM db_clock)
        ELSE auth_rate_limit.window_started_at
    END
RETURNING count,
    GREATEST(0, CEIL(EXTRACT(EPOCH FROM (window_started_at + interval '1 minute' - (SELECT now FROM db_clock)))))::integer AS retry_after_seconds
`

type UpsertAdminLoginRateLimitRow struct {
	Count             int32 `json:"count"`
	RetryAfterSeconds int32 `json:"retry_after_seconds"`
}

func (q *Queries) UpsertAdminLoginRateLimit(ctx context.Context, subject string) (UpsertAdminLoginRateLimitRow, error) {
	row := q.db.QueryRow(ctx, upsertAdminLoginRateLimit, subject)
	var i UpsertAdminLoginRateLimitRow
	err := row.Scan(&i.Count, &i.RetryAfterSeconds)
	return i, err
}

const upsertAuthRateLimit = `-- name: UpsertAuthRateLimit :one
WITH db_clock AS MATERIALIZED (
    SELECT clock_timestamp() AS now
)
INSERT INTO auth_rate_limit (scope, subject, window_started_at, count)
SELECT $1, $2, db_clock.now, 1
FROM db_clock
ON CONFLICT (scope, subject) DO UPDATE
SET count = CASE
        WHEN auth_rate_limit.window_started_at <= (SELECT now FROM db_clock) - interval '1 minute' THEN 1
        ELSE auth_rate_limit.count + 1
    END,
    window_started_at = CASE
        WHEN auth_rate_limit.window_started_at <= (SELECT now FROM db_clock) - interval '1 minute' THEN (SELECT now FROM db_clock)
        ELSE auth_rate_limit.window_started_at
    END
RETURNING count, window_started_at,
    GREATEST(0, CEIL(EXTRACT(EPOCH FROM (window_started_at + interval '1 minute' - (SELECT now FROM db_clock)))))::integer AS retry_after_seconds
`

type UpsertAuthRateLimitParams struct {
	Scope   string `json:"scope"`
	Subject string `json:"subject"`
}

type UpsertAuthRateLimitRow struct {
	Count             int32              `json:"count"`
	WindowStartedAt   pgtype.Timestamptz `json:"window_started_at"`
	RetryAfterSeconds int32              `json:"retry_after_seconds"`
}

func (q *Queries) UpsertAuthRateLimit(ctx context.Context, arg UpsertAuthRateLimitParams) (UpsertAuthRateLimitRow, error) {
	row := q.db.QueryRow(ctx, upsertAuthRateLimit, arg.Scope, arg.Subject)
	var i UpsertAuthRateLimitRow
	err := row.Scan(&i.Count, &i.WindowStartedAt, &i.RetryAfterSeconds)
	return i, err
}
