// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PairRelationshipType string

const (
	PairRelationshipTypePartner PairRelationshipType = "partner"
	PairRelationshipTypeFriend  PairRelationshipType = "friend"
)

func (e *PairRelationshipType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PairRelationshipType(s)
	case string:
		*e = PairRelationshipType(s)
	default:
		return fmt.Errorf("unsupported scan type for PairRelationshipType: %T", src)
	}
	return nil
}

type NullPairRelationshipType struct {
	PairRelationshipType PairRelationshipType `json:"pair_relationship_type"`
	Valid                bool                 `json:"valid"` // Valid is true if PairRelationshipType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPairRelationshipType) Scan(value interface{}) error {
	if value == nil {
		ns.PairRelationshipType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PairRelationshipType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPairRelationshipType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PairRelationshipType), nil
}

type PairSlot string

const (
	PairSlotFirst  PairSlot = "first"
	PairSlotSecond PairSlot = "second"
)

func (e *PairSlot) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PairSlot(s)
	case string:
		*e = PairSlot(s)
	default:
		return fmt.Errorf("unsupported scan type for PairSlot: %T", src)
	}
	return nil
}

type NullPairSlot struct {
	PairSlot PairSlot `json:"pair_slot"`
	Valid    bool     `json:"valid"` // Valid is true if PairSlot is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPairSlot) Scan(value interface{}) error {
	if value == nil {
		ns.PairSlot, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PairSlot.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPairSlot) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PairSlot), nil
}

type PrivateQuestionCandidateState string

const (
	PrivateQuestionCandidateStateUnresolved  PrivateQuestionCandidateState = "unresolved"
	PrivateQuestionCandidateStateAsked       PrivateQuestionCandidateState = "asked"
	PrivateQuestionCandidateStateSkipped     PrivateQuestionCandidateState = "skipped"
	PrivateQuestionCandidateStateInvalidated PrivateQuestionCandidateState = "invalidated"
)

func (e *PrivateQuestionCandidateState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrivateQuestionCandidateState(s)
	case string:
		*e = PrivateQuestionCandidateState(s)
	default:
		return fmt.Errorf("unsupported scan type for PrivateQuestionCandidateState: %T", src)
	}
	return nil
}

type NullPrivateQuestionCandidateState struct {
	PrivateQuestionCandidateState PrivateQuestionCandidateState `json:"private_question_candidate_state"`
	Valid                         bool                          `json:"valid"` // Valid is true if PrivateQuestionCandidateState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrivateQuestionCandidateState) Scan(value interface{}) error {
	if value == nil {
		ns.PrivateQuestionCandidateState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrivateQuestionCandidateState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrivateQuestionCandidateState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrivateQuestionCandidateState), nil
}

type PrivateReactionValue string

const (
	PrivateReactionValueHeart     PrivateReactionValue = "heart"
	PrivateReactionValueLaugh     PrivateReactionValue = "laugh"
	PrivateReactionValueTender    PrivateReactionValue = "tender"
	PrivateReactionValueSurprised PrivateReactionValue = "surprised"
)

func (e *PrivateReactionValue) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrivateReactionValue(s)
	case string:
		*e = PrivateReactionValue(s)
	default:
		return fmt.Errorf("unsupported scan type for PrivateReactionValue: %T", src)
	}
	return nil
}

type NullPrivateReactionValue struct {
	PrivateReactionValue PrivateReactionValue `json:"private_reaction_value"`
	Valid                bool                 `json:"valid"` // Valid is true if PrivateReactionValue is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrivateReactionValue) Scan(value interface{}) error {
	if value == nil {
		ns.PrivateReactionValue, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrivateReactionValue.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrivateReactionValue) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrivateReactionValue), nil
}

type PrivateRoundStatus string

const (
	PrivateRoundStatusOpen      PrivateRoundStatus = "open"
	PrivateRoundStatusCompleted PrivateRoundStatus = "completed"
	PrivateRoundStatusRetired   PrivateRoundStatus = "retired"
)

func (e *PrivateRoundStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrivateRoundStatus(s)
	case string:
		*e = PrivateRoundStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PrivateRoundStatus: %T", src)
	}
	return nil
}

type NullPrivateRoundStatus struct {
	PrivateRoundStatus PrivateRoundStatus `json:"private_round_status"`
	Valid              bool               `json:"valid"` // Valid is true if PrivateRoundStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrivateRoundStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PrivateRoundStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrivateRoundStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrivateRoundStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrivateRoundStatus), nil
}

type AdminUser struct {
	AuthUserID pgtype.UUID        `json:"auth_user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthCredential struct {
	AuthUserID        pgtype.UUID        `json:"auth_user_id"`
	EmailNormalized   string             `json:"email_normalized"`
	PasswordHash      string             `json:"password_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	PasswordUpdatedAt pgtype.Timestamptz `json:"password_updated_at"`
}

type AuthRateLimit struct {
	Scope           string             `json:"scope"`
	Subject         string             `json:"subject"`
	WindowStartedAt pgtype.Timestamptz `json:"window_started_at"`
	Count           int32              `json:"count"`
}

type AuthSession struct {
	ID         pgtype.UUID        `json:"id"`
	AuthUserID pgtype.UUID        `json:"auth_user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type AuthUser struct {
	ID         pgtype.UUID        `json:"id"`
	Kind       string             `json:"kind"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
}

type InitialInvite struct {
	ID                      pgtype.UUID        `json:"id"`
	PairID                  pgtype.UUID        `json:"pair_id"`
	TokenHash               []byte             `json:"token_hash"`
	IssuedByParticipantID   pgtype.UUID        `json:"issued_by_participant_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	RevokedAt               pgtype.Timestamptz `json:"revoked_at"`
	RedeemedAt              pgtype.Timestamptz `json:"redeemed_at"`
	RedeemedByParticipantID pgtype.UUID        `json:"redeemed_by_participant_id"`
}

type Pair struct {
	ID                 pgtype.UUID          `json:"id"`
	RelationshipType   PairRelationshipType `json:"relationship_type"`
	IntendedPersonName pgtype.Text          `json:"intended_person_name"`
	CreationRequestID  pgtype.UUID          `json:"creation_request_id"`
	TerminatedAt       pgtype.Timestamptz   `json:"terminated_at"`
	CreatedAt          pgtype.Timestamptz   `json:"created_at"`
}

type PairMembership struct {
	ID               pgtype.UUID        `json:"id"`
	PairID           pgtype.UUID        `json:"pair_id"`
	ParticipantID    pgtype.UUID        `json:"participant_id"`
	Slot             PairSlot           `json:"slot"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	EndedDisplayName pgtype.Text        `json:"ended_display_name"`
}

type PairMembershipEra struct {
	ID                 pgtype.UUID        `json:"id"`
	PairID             pgtype.UUID        `json:"pair_id"`
	FirstMembershipID  pgtype.UUID        `json:"first_membership_id"`
	SecondMembershipID pgtype.UUID        `json:"second_membership_id"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	FirstSlot          PairSlot           `json:"first_slot"`
	SecondSlot         PairSlot           `json:"second_slot"`
}

type Participant struct {
	ID          pgtype.UUID        `json:"id"`
	AuthUserID  pgtype.UUID        `json:"auth_user_id"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PrivateAnswer struct {
	ID              pgtype.UUID        `json:"id"`
	RoundID         pgtype.UUID        `json:"round_id"`
	MembershipEraID pgtype.UUID        `json:"membership_era_id"`
	MembershipID    pgtype.UUID        `json:"membership_id"`
	ParticipantID   pgtype.UUID        `json:"participant_id"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PrivateConversation struct {
	ID                     pgtype.UUID        `json:"id"`
	PairID                 pgtype.UUID        `json:"pair_id"`
	Category               string             `json:"category"`
	CreatedByParticipantID pgtype.UUID        `json:"created_by_participant_id"`
	MembershipEraID        pgtype.UUID        `json:"membership_era_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	SelectionSeed          string             `json:"selection_seed"`
}

type PrivateQuestionCandidate struct {
	ID                    pgtype.UUID                   `json:"id"`
	ConversationID        pgtype.UUID                   `json:"conversation_id"`
	QuestionID            pgtype.UUID                   `json:"question_id"`
	QuestionRevisionID    pgtype.UUID                   `json:"question_revision_id"`
	State                 PrivateQuestionCandidateState `json:"state"`
	CreatedAt             pgtype.Timestamptz            `json:"created_at"`
	ResolvedAt            pgtype.Timestamptz            `json:"resolved_at"`
	LikedAt               pgtype.Timestamptz            `json:"liked_at"`
	SkipRequestID         pgtype.UUID                   `json:"skip_request_id"`
	SkipResultCandidateID pgtype.UUID                   `json:"skip_result_candidate_id"`
}

type PrivateReaction struct {
	ID              pgtype.UUID          `json:"id"`
	RoundID         pgtype.UUID          `json:"round_id"`
	MembershipEraID pgtype.UUID          `json:"membership_era_id"`
	MembershipID    pgtype.UUID          `json:"membership_id"`
	ParticipantID   pgtype.UUID          `json:"participant_id"`
	Value           PrivateReactionValue `json:"value"`
	UpdatedAt       pgtype.Timestamptz   `json:"updated_at"`
}

type PrivateReply struct {
	ID              pgtype.UUID        `json:"id"`
	RoundID         pgtype.UUID        `json:"round_id"`
	MembershipEraID pgtype.UUID        `json:"membership_era_id"`
	MembershipID    pgtype.UUID        `json:"membership_id"`
	ParticipantID   pgtype.UUID        `json:"participant_id"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PrivateRevealView struct {
	ID              pgtype.UUID        `json:"id"`
	RoundID         pgtype.UUID        `json:"round_id"`
	MembershipEraID pgtype.UUID        `json:"membership_era_id"`
	MembershipID    pgtype.UUID        `json:"membership_id"`
	ParticipantID   pgtype.UUID        `json:"participant_id"`
	ViewedAt        pgtype.Timestamptz `json:"viewed_at"`
}

type PrivateRound struct {
	ID                        pgtype.UUID        `json:"id"`
	PairID                    pgtype.UUID        `json:"pair_id"`
	ConversationID            pgtype.UUID        `json:"conversation_id"`
	MembershipEraID           pgtype.UUID        `json:"membership_era_id"`
	CandidateID               pgtype.UUID        `json:"candidate_id"`
	QuestionID                pgtype.UUID        `json:"question_id"`
	QuestionRevisionID        pgtype.UUID        `json:"question_revision_id"`
	RoundNumber               int32              `json:"round_number"`
	Status                    PrivateRoundStatus `json:"status"`
	DeclinedByMembershipID    pgtype.UUID        `json:"declined_by_membership_id"`
	DeclinedAt                pgtype.Timestamptz `json:"declined_at"`
	AskedAt                   pgtype.Timestamptz `json:"asked_at"`
	ClientRequestID           pgtype.UUID        `json:"client_request_id"`
	ProgressionRequestID      pgtype.UUID        `json:"progression_request_id"`
	ProgressionAction         pgtype.Text        `json:"progression_action"`
	ProgressionCategory       pgtype.Text        `json:"progression_category"`
	ProgressionConversationID pgtype.UUID        `json:"progression_conversation_id"`
	ProgressionCandidateID    pgtype.UUID        `json:"progression_candidate_id"`
	ProgressionExhausted      bool               `json:"progression_exhausted"`
	ProgressionWaiting        bool               `json:"progression_waiting"`
}

type Question struct {
	ID                pgtype.UUID        `json:"id"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type QuestionLifecycleEvent struct {
	ID          pgtype.UUID        `json:"id"`
	QuestionID  pgtype.UUID        `json:"question_id"`
	RevisionID  pgtype.UUID        `json:"revision_id"`
	Action      string             `json:"action"`
	AdminUserID pgtype.UUID        `json:"admin_user_id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Reason      pgtype.Text        `json:"reason"`
}

type QuestionRevision struct {
	ID                     pgtype.UUID        `json:"id"`
	QuestionID             pgtype.UUID        `json:"question_id"`
	Text                   string             `json:"text"`
	Category               string             `json:"category"`
	RelationshipFit        string             `json:"relationship_fit"`
	ModeFit                string             `json:"mode_fit"`
	Intensity              string             `json:"intensity"`
	RevisionNumber         int32              `json:"revision_number"`
	CreatedByAdminUserID   pgtype.UUID        `json:"created_by_admin_user_id"`
	WithdrawnAt            pgtype.Timestamptz `json:"withdrawn_at"`
	WithdrawnReason        pgtype.Text        `json:"withdrawn_reason"`
	WithdrawnByAdminUserID pgtype.UUID        `json:"withdrawn_by_admin_user_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type RejoinInvite struct {
	ID                      pgtype.UUID        `json:"id"`
	PairID                  pgtype.UUID        `json:"pair_id"`
	TargetSlot              PairSlot           `json:"target_slot"`
	TargetParticipantID     pgtype.UUID        `json:"target_participant_id"`
	TokenHash               []byte             `json:"token_hash"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	RevokedAt               pgtype.Timestamptz `json:"revoked_at"`
	RedeemedAt              pgtype.Timestamptz `json:"redeemed_at"`
	RedeemedByParticipantID pgtype.UUID        `json:"redeemed_by_participant_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type TogetherSession struct {
	ID                     pgtype.UUID        `json:"id"`
	PairID                 pgtype.UUID        `json:"pair_id"`
	MembershipEraID        pgtype.UUID        `json:"membership_era_id"`
	Category               string             `json:"category"`
	StartedByParticipantID pgtype.UUID        `json:"started_by_participant_id"`
	StartRequestID         pgtype.UUID        `json:"start_request_id"`
	SelectionSeed          string             `json:"selection_seed"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	EndedAt                pgtype.Timestamptz `json:"ended_at"`
}

type TogetherSessionQuestion struct {
	ID                 pgtype.UUID        `json:"id"`
	SessionID          pgtype.UUID        `json:"session_id"`
	QuestionID         pgtype.UUID        `json:"question_id"`
	QuestionRevisionID pgtype.UUID        `json:"question_revision_id"`
	Position           int32              `json:"position"`
	ShownAt            pgtype.Timestamptz `json:"shown_at"`
	LikedAt            pgtype.Timestamptz `json:"liked_at"`
	SkippedAt          pgtype.Timestamptz `json:"skipped_at"`
	AdvancedAt         pgtype.Timestamptz `json:"advanced_at"`
	AdvanceRequestID   pgtype.UUID        `json:"advance_request_id"`
}
