// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pair.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCreatorMembership = `-- name: CreateCreatorMembership :one
INSERT INTO pair_membership (pair_id, participant_id, slot)
VALUES ($1, $2, 'first')
RETURNING id, pair_id, participant_id, slot, started_at, ended_at, ended_display_name
`

type CreateCreatorMembershipParams struct {
	PairID        pgtype.UUID `json:"pair_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

func (q *Queries) CreateCreatorMembership(ctx context.Context, arg CreateCreatorMembershipParams) (PairMembership, error) {
	row := q.db.QueryRow(ctx, createCreatorMembership, arg.PairID, arg.ParticipantID)
	var i PairMembership
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.ParticipantID,
		&i.Slot,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndedDisplayName,
	)
	return i, err
}

const createPair = `-- name: CreatePair :one
INSERT INTO pair (relationship_type, intended_person_name, creation_request_id)
VALUES ($1, $2, $3)
ON CONFLICT (creation_request_id) DO NOTHING
RETURNING id, relationship_type, intended_person_name, creation_request_id, terminated_at, created_at
`

type CreatePairParams struct {
	RelationshipType   PairRelationshipType `json:"relationship_type"`
	IntendedPersonName pgtype.Text          `json:"intended_person_name"`
	CreationRequestID  pgtype.UUID          `json:"creation_request_id"`
}

func (q *Queries) CreatePair(ctx context.Context, arg CreatePairParams) (Pair, error) {
	row := q.db.QueryRow(ctx, createPair, arg.RelationshipType, arg.IntendedPersonName, arg.CreationRequestID)
	var i Pair
	err := row.Scan(
		&i.ID,
		&i.RelationshipType,
		&i.IntendedPersonName,
		&i.CreationRequestID,
		&i.TerminatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const endActiveErasForTermination = `-- name: EndActiveErasForTermination :execrows
UPDATE pair_membership_era
SET ended_at = p.terminated_at
FROM pair AS p
WHERE p.id = $1
  AND pair_membership_era.pair_id = p.id
  AND pair_membership_era.ended_at IS NULL
  AND p.terminated_at IS NOT NULL
`

func (q *Queries) EndActiveErasForTermination(ctx context.Context, pairID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, endActiveErasForTermination, pairID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endActiveMembershipsForTermination = `-- name: EndActiveMembershipsForTermination :execrows
UPDATE pair_membership AS membership
SET ended_at = p.terminated_at,
    ended_display_name = participant.display_name
FROM pair AS p, participant
WHERE p.id = $1
  AND membership.pair_id = p.id
  AND membership.ended_at IS NULL
  AND participant.id = membership.participant_id
  AND p.terminated_at IS NOT NULL
`

func (q *Queries) EndActiveMembershipsForTermination(ctx context.Context, pairID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, endActiveMembershipsForTermination, pairID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endTogetherSessionsForTermination = `-- name: EndTogetherSessionsForTermination :execrows
UPDATE together_session
SET ended_at = p.terminated_at
FROM pair AS p
WHERE p.id = $1
  AND p.terminated_at IS NOT NULL
  AND together_session.pair_id = p.id
  AND together_session.ended_at IS NULL
`

func (q *Queries) EndTogetherSessionsForTermination(ctx context.Context, pairID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, endTogetherSessionsForTermination, pairID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findFormerTerminatedPair = `-- name: FindFormerTerminatedPair :one
SELECT p.id
FROM pair AS p
JOIN pair_membership AS m ON m.pair_id = p.id
WHERE p.id = $1
  AND p.terminated_at IS NOT NULL
  AND m.participant_id = $2
LIMIT 1
`

type FindFormerTerminatedPairParams struct {
	PairID        pgtype.UUID `json:"pair_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

func (q *Queries) FindFormerTerminatedPair(ctx context.Context, arg FindFormerTerminatedPairParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findFormerTerminatedPair, arg.PairID, arg.ParticipantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getActivePairAccess = `-- name: GetActivePairAccess :one
SELECT
    p.id AS pair_id,
    p.relationship_type,
    p.intended_person_name,
    p.terminated_at,
    actor_membership.id AS actor_membership_id,
    actor_membership.slot AS actor_slot,
    other_membership.id AS other_membership_id,
    other_membership.participant_id AS other_participant_id,
    other_participant.display_name AS other_participant_display_name,
    active_era.id AS membership_era_id
FROM pair AS p
JOIN pair_membership AS actor_membership
    ON actor_membership.pair_id = p.id
   AND actor_membership.participant_id = $1
   AND actor_membership.ended_at IS NULL
LEFT JOIN pair_membership AS other_membership
    ON other_membership.pair_id = p.id
   AND other_membership.slot <> actor_membership.slot
   AND other_membership.ended_at IS NULL
LEFT JOIN participant AS other_participant
    ON other_participant.id = other_membership.participant_id
LEFT JOIN pair_membership_era AS active_era
    ON active_era.pair_id = p.id
   AND active_era.ended_at IS NULL
WHERE p.id = $2
  AND p.terminated_at IS NULL
`

type GetActivePairAccessParams struct {
	ParticipantID pgtype.UUID `json:"participant_id"`
	PairID        pgtype.UUID `json:"pair_id"`
}

type GetActivePairAccessRow struct {
	PairID                      pgtype.UUID          `json:"pair_id"`
	RelationshipType            PairRelationshipType `json:"relationship_type"`
	IntendedPersonName          pgtype.Text          `json:"intended_person_name"`
	TerminatedAt                pgtype.Timestamptz   `json:"terminated_at"`
	ActorMembershipID           pgtype.UUID          `json:"actor_membership_id"`
	ActorSlot                   PairSlot             `json:"actor_slot"`
	OtherMembershipID           pgtype.UUID          `json:"other_membership_id"`
	OtherParticipantID          pgtype.UUID          `json:"other_participant_id"`
	OtherParticipantDisplayName pgtype.Text          `json:"other_participant_display_name"`
	MembershipEraID             pgtype.UUID          `json:"membership_era_id"`
}

func (q *Queries) GetActivePairAccess(ctx context.Context, arg GetActivePairAccessParams) (GetActivePairAccessRow, error) {
	row := q.db.QueryRow(ctx, getActivePairAccess, arg.ParticipantID, arg.PairID)
	var i GetActivePairAccessRow
	err := row.Scan(
		&i.PairID,
		&i.RelationshipType,
		&i.IntendedPersonName,
		&i.TerminatedAt,
		&i.ActorMembershipID,
		&i.ActorSlot,
		&i.OtherMembershipID,
		&i.OtherParticipantID,
		&i.OtherParticipantDisplayName,
		&i.MembershipEraID,
	)
	return i, err
}

const getCreatedPairByRequestAndParticipant = `-- name: GetCreatedPairByRequestAndParticipant :one
SELECT p.id, p.relationship_type, p.intended_person_name, p.creation_request_id, p.terminated_at, p.created_at
FROM pair AS p
JOIN pair_membership AS m ON m.pair_id = p.id
WHERE p.creation_request_id = $1
  AND m.participant_id = $2
  AND m.slot = 'first'
  AND m.ended_at IS NULL
`

type GetCreatedPairByRequestAndParticipantParams struct {
	CreationRequestID pgtype.UUID `json:"creation_request_id"`
	ParticipantID     pgtype.UUID `json:"participant_id"`
}

func (q *Queries) GetCreatedPairByRequestAndParticipant(ctx context.Context, arg GetCreatedPairByRequestAndParticipantParams) (Pair, error) {
	row := q.db.QueryRow(ctx, getCreatedPairByRequestAndParticipant, arg.CreationRequestID, arg.ParticipantID)
	var i Pair
	err := row.Scan(
		&i.ID,
		&i.RelationshipType,
		&i.IntendedPersonName,
		&i.CreationRequestID,
		&i.TerminatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasActiveSecondSlot = `-- name: HasActiveSecondSlot :one
SELECT EXISTS (
    SELECT 1 FROM pair_membership
    WHERE pair_id = $1
      AND slot = 'second'
      AND ended_at IS NULL
)::boolean
`

func (q *Queries) HasActiveSecondSlot(ctx context.Context, pairID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveSecondSlot, pairID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const invalidateCandidatesForTermination = `-- name: InvalidateCandidatesForTermination :execrows
UPDATE private_question_candidate AS candidate
SET state = 'invalidated', resolved_at = p.terminated_at
FROM private_conversation AS conversation, pair AS p
WHERE p.id = $1
  AND p.terminated_at IS NOT NULL
  AND conversation.pair_id = p.id
  AND candidate.conversation_id = conversation.id
  AND candidate.state = 'unresolved'
`

func (q *Queries) InvalidateCandidatesForTermination(ctx context.Context, pairID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateCandidatesForTermination, pairID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActivePairMembers = `-- name: ListActivePairMembers :many
SELECT m.participant_id, m.slot, p.display_name
FROM pair_membership AS m
JOIN participant AS p ON p.id = m.participant_id
WHERE m.pair_id = $1
  AND m.ended_at IS NULL
ORDER BY m.slot
`

type ListActivePairMembersRow struct {
	ParticipantID pgtype.UUID `json:"participant_id"`
	Slot          PairSlot    `json:"slot"`
	DisplayName   string      `json:"display_name"`
}

func (q *Queries) ListActivePairMembers(ctx context.Context, pairID pgtype.UUID) ([]ListActivePairMembersRow, error) {
	rows, err := q.db.Query(ctx, listActivePairMembers, pairID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePairMembersRow
	for rows.Next() {
		var i ListActivePairMembersRow
		if err := rows.Scan(&i.ParticipantID, &i.Slot, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantSpaces = `-- name: ListParticipantSpaces :many
SELECT
    p.id AS pair_id,
    p.relationship_type,
    p.intended_person_name,
    actor_membership.slot AS actor_slot,
    other_participant.id AS other_participant_id,
    other_participant.display_name AS other_participant_display_name,
    CASE WHEN other_membership.id IS NULL THEN 'waiting' ELSE 'connected' END::text AS state
FROM pair AS p
JOIN pair_membership AS actor_membership
    ON actor_membership.pair_id = p.id
   AND actor_membership.participant_id = $1
   AND actor_membership.ended_at IS NULL
LEFT JOIN pair_membership AS other_membership
    ON other_membership.pair_id = p.id
   AND other_membership.slot <> actor_membership.slot
   AND other_membership.ended_at IS NULL
LEFT JOIN participant AS other_participant
    ON other_participant.id = other_membership.participant_id
WHERE p.terminated_at IS NULL
ORDER BY p.created_at DESC, p.id DESC
`

type ListParticipantSpacesRow struct {
	PairID                      pgtype.UUID          `json:"pair_id"`
	RelationshipType            PairRelationshipType `json:"relationship_type"`
	IntendedPersonName          pgtype.Text          `json:"intended_person_name"`
	ActorSlot                   PairSlot             `json:"actor_slot"`
	OtherParticipantID          pgtype.UUID          `json:"other_participant_id"`
	OtherParticipantDisplayName pgtype.Text          `json:"other_participant_display_name"`
	State                       string               `json:"state"`
}

func (q *Queries) ListParticipantSpaces(ctx context.Context, participantID pgtype.UUID) ([]ListParticipantSpacesRow, error) {
	rows, err := q.db.Query(ctx, listParticipantSpaces, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantSpacesRow
	for rows.Next() {
		var i ListParticipantSpacesRow
		if err := rows.Scan(
			&i.PairID,
			&i.RelationshipType,
			&i.IntendedPersonName,
			&i.ActorSlot,
			&i.OtherParticipantID,
			&i.OtherParticipantDisplayName,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActivePair = `-- name: LockActivePair :one
SELECT id
FROM pair
WHERE id = $1
  AND terminated_at IS NULL
FOR UPDATE
`

func (q *Queries) LockActivePair(ctx context.Context, pairID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockActivePair, pairID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockPairForTermination = `-- name: LockPairForTermination :one
SELECT id, terminated_at
FROM pair
WHERE id = $1
FOR UPDATE
`

type LockPairForTerminationRow struct {
	ID           pgtype.UUID        `json:"id"`
	TerminatedAt pgtype.Timestamptz `json:"terminated_at"`
}

func (q *Queries) LockPairForTermination(ctx context.Context, pairID pgtype.UUID) (LockPairForTerminationRow, error) {
	row := q.db.QueryRow(ctx, lockPairForTermination, pairID)
	var i LockPairForTerminationRow
	err := row.Scan(&i.ID, &i.TerminatedAt)
	return i, err
}

const markPairTerminated = `-- name: MarkPairTerminated :one
UPDATE pair
SET terminated_at = clock_timestamp()
WHERE id = $1
  AND terminated_at IS NULL
RETURNING terminated_at
`

func (q *Queries) MarkPairTerminated(ctx context.Context, pairID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, markPairTerminated, pairID)
	var terminated_at pgtype.Timestamptz
	err := row.Scan(&terminated_at)
	return terminated_at, err
}

const participantExists = `-- name: ParticipantExists :one
SELECT EXISTS (SELECT 1 FROM participant WHERE id = $1)::boolean
`

func (q *Queries) ParticipantExists(ctx context.Context, participantID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, participantExists, participantID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const participantHasActiveMembership = `-- name: ParticipantHasActiveMembership :one
SELECT EXISTS (
    SELECT 1 FROM pair_membership
    WHERE pair_id = $1
      AND participant_id = $2
      AND ended_at IS NULL
)::boolean
`

type ParticipantHasActiveMembershipParams struct {
	PairID        pgtype.UUID `json:"pair_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

func (q *Queries) ParticipantHasActiveMembership(ctx context.Context, arg ParticipantHasActiveMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, participantHasActiveMembership, arg.PairID, arg.ParticipantID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const participantMembershipState = `-- name: ParticipantMembershipState :one
SELECT
    EXISTS (
        SELECT 1 FROM pair_membership AS membership
        WHERE membership.pair_id = $1
          AND membership.participant_id = $2
    )::boolean AS has_membership,
    EXISTS (
        SELECT 1 FROM pair_membership AS membership
        WHERE membership.pair_id = $1
          AND membership.participant_id = $2
          AND membership.ended_at IS NULL
    )::boolean AS has_active_membership
`

type ParticipantMembershipStateParams struct {
	PairID        pgtype.UUID `json:"pair_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

type ParticipantMembershipStateRow struct {
	HasMembership       bool `json:"has_membership"`
	HasActiveMembership bool `json:"has_active_membership"`
}

func (q *Queries) ParticipantMembershipState(ctx context.Context, arg ParticipantMembershipStateParams) (ParticipantMembershipStateRow, error) {
	row := q.db.QueryRow(ctx, participantMembershipState, arg.PairID, arg.ParticipantID)
	var i ParticipantMembershipStateRow
	err := row.Scan(&i.HasMembership, &i.HasActiveMembership)
	return i, err
}

const revokeInitialInvitesForTermination = `-- name: RevokeInitialInvitesForTermination :execrows
UPDATE initial_invite
SET revoked_at = p.terminated_at
FROM pair AS p
WHERE p.id = $1
  AND p.terminated_at IS NOT NULL
  AND initial_invite.pair_id = p.id
  AND initial_invite.revoked_at IS NULL
  AND initial_invite.redeemed_at IS NULL
`

func (q *Queries) RevokeInitialInvitesForTermination(ctx context.Context, pairID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInitialInvitesForTermination, pairID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRejoinInvitesForTermination = `-- name: RevokeRejoinInvitesForTermination :execrows
UPDATE rejoin_invite
SET revoked_at = p.terminated_at
FROM pair AS p
WHERE p.id = $1
  AND p.terminated_at IS NOT NULL
  AND rejoin_invite.pair_id = p.id
  AND rejoin_invite.revoked_at IS NULL
  AND rejoin_invite.redeemed_at IS NULL
`

func (q *Queries) RevokeRejoinInvitesForTermination(ctx context.Context, pairID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRejoinInvitesForTermination, pairID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIntendedPersonName = `-- name: UpdateIntendedPersonName :one
UPDATE pair
SET intended_person_name = $1
WHERE id = $2
  AND terminated_at IS NULL
RETURNING id, relationship_type, intended_person_name, creation_request_id, terminated_at, created_at
`

type UpdateIntendedPersonNameParams struct {
	IntendedPersonName pgtype.Text `json:"intended_person_name"`
	PairID             pgtype.UUID `json:"pair_id"`
}

func (q *Queries) UpdateIntendedPersonName(ctx context.Context, arg UpdateIntendedPersonNameParams) (Pair, error) {
	row := q.db.QueryRow(ctx, updateIntendedPersonName, arg.IntendedPersonName, arg.PairID)
	var i Pair
	err := row.Scan(
		&i.ID,
		&i.RelationshipType,
		&i.IntendedPersonName,
		&i.CreationRequestID,
		&i.TerminatedAt,
		&i.CreatedAt,
	)
	return i, err
}
