// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participant.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participant (auth_user_id, display_name)
VALUES ($1, $2)
ON CONFLICT (auth_user_id) DO NOTHING
RETURNING id, auth_user_id, display_name, created_at, updated_at
`

type CreateParticipantParams struct {
	AuthUserID  pgtype.UUID `json:"auth_user_id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant, arg.AuthUserID, arg.DisplayName)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipantByAuthUserID = `-- name: GetParticipantByAuthUserID :one
SELECT id, auth_user_id, display_name, created_at, updated_at
FROM participant
WHERE auth_user_id = $1
`

func (q *Queries) GetParticipantByAuthUserID(ctx context.Context, authUserID pgtype.UUID) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByAuthUserID, authUserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipantByID = `-- name: GetParticipantByID :one
SELECT id, auth_user_id, display_name, created_at, updated_at
FROM participant
WHERE id = $1
`

func (q *Queries) GetParticipantByID(ctx context.Context, id pgtype.UUID) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByID, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
