// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: private.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrivateAnswer = `-- name: CreatePrivateAnswer :one
INSERT INTO private_answer (round_id, membership_era_id, membership_id, participant_id, body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (round_id, membership_id) DO NOTHING
RETURNING id, round_id, membership_era_id, membership_id, participant_id, body, created_at
`

type CreatePrivateAnswerParams struct {
	RoundID         pgtype.UUID `json:"round_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
	MembershipID    pgtype.UUID `json:"membership_id"`
	ParticipantID   pgtype.UUID `json:"participant_id"`
	Body            string      `json:"body"`
}

func (q *Queries) CreatePrivateAnswer(ctx context.Context, arg CreatePrivateAnswerParams) (PrivateAnswer, error) {
	row := q.db.QueryRow(ctx, createPrivateAnswer,
		arg.RoundID,
		arg.MembershipEraID,
		arg.MembershipID,
		arg.ParticipantID,
		arg.Body,
	)
	var i PrivateAnswer
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.MembershipEraID,
		&i.MembershipID,
		&i.ParticipantID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createPrivateConversation = `-- name: CreatePrivateConversation :one
INSERT INTO private_conversation (pair_id, category, created_by_participant_id, membership_era_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (pair_id, membership_era_id, category) DO NOTHING
RETURNING id, pair_id, category, created_by_participant_id, membership_era_id, created_at, selection_seed
`

type CreatePrivateConversationParams struct {
	PairID                 pgtype.UUID `json:"pair_id"`
	Category               string      `json:"category"`
	CreatedByParticipantID pgtype.UUID `json:"created_by_participant_id"`
	MembershipEraID        pgtype.UUID `json:"membership_era_id"`
}

func (q *Queries) CreatePrivateConversation(ctx context.Context, arg CreatePrivateConversationParams) (PrivateConversation, error) {
	row := q.db.QueryRow(ctx, createPrivateConversation,
		arg.PairID,
		arg.Category,
		arg.CreatedByParticipantID,
		arg.MembershipEraID,
	)
	var i PrivateConversation
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.Category,
		&i.CreatedByParticipantID,
		&i.MembershipEraID,
		&i.CreatedAt,
		&i.SelectionSeed,
	)
	return i, err
}

const createPrivateQuestionCandidate = `-- name: CreatePrivateQuestionCandidate :one
INSERT INTO private_question_candidate (conversation_id, question_id, question_revision_id)
VALUES ($1, $2, $3)
ON CONFLICT (conversation_id) WHERE state = 'unresolved' DO NOTHING
RETURNING id, conversation_id, question_id, question_revision_id, state, created_at, resolved_at
`

type CreatePrivateQuestionCandidateParams struct {
	ConversationID     pgtype.UUID `json:"conversation_id"`
	QuestionID         pgtype.UUID `json:"question_id"`
	QuestionRevisionID pgtype.UUID `json:"question_revision_id"`
}

type CreatePrivateQuestionCandidateRow struct {
	ID                 pgtype.UUID                   `json:"id"`
	ConversationID     pgtype.UUID                   `json:"conversation_id"`
	QuestionID         pgtype.UUID                   `json:"question_id"`
	QuestionRevisionID pgtype.UUID                   `json:"question_revision_id"`
	State              PrivateQuestionCandidateState `json:"state"`
	CreatedAt          pgtype.Timestamptz            `json:"created_at"`
	ResolvedAt         pgtype.Timestamptz            `json:"resolved_at"`
}

func (q *Queries) CreatePrivateQuestionCandidate(ctx context.Context, arg CreatePrivateQuestionCandidateParams) (CreatePrivateQuestionCandidateRow, error) {
	row := q.db.QueryRow(ctx, createPrivateQuestionCandidate, arg.ConversationID, arg.QuestionID, arg.QuestionRevisionID)
	var i CreatePrivateQuestionCandidateRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.State,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createPrivateRevealView = `-- name: CreatePrivateRevealView :one
INSERT INTO private_reveal_view (round_id, membership_era_id, membership_id, participant_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (round_id, membership_id) DO NOTHING
RETURNING id, round_id, membership_era_id, membership_id, participant_id, viewed_at
`

type CreatePrivateRevealViewParams struct {
	RoundID         pgtype.UUID `json:"round_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
	MembershipID    pgtype.UUID `json:"membership_id"`
	ParticipantID   pgtype.UUID `json:"participant_id"`
}

func (q *Queries) CreatePrivateRevealView(ctx context.Context, arg CreatePrivateRevealViewParams) (PrivateRevealView, error) {
	row := q.db.QueryRow(ctx, createPrivateRevealView,
		arg.RoundID,
		arg.MembershipEraID,
		arg.MembershipID,
		arg.ParticipantID,
	)
	var i PrivateRevealView
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.MembershipEraID,
		&i.MembershipID,
		&i.ParticipantID,
		&i.ViewedAt,
	)
	return i, err
}

const createPrivateRound = `-- name: CreatePrivateRound :one
INSERT INTO private_round (
    pair_id, conversation_id, membership_era_id, candidate_id,
    question_id, question_revision_id, round_number, client_request_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, pair_id, conversation_id, membership_era_id, candidate_id, question_id,
          question_revision_id, round_number, status, asked_at, client_request_id
`

type CreatePrivateRoundParams struct {
	PairID             pgtype.UUID `json:"pair_id"`
	ConversationID     pgtype.UUID `json:"conversation_id"`
	MembershipEraID    pgtype.UUID `json:"membership_era_id"`
	CandidateID        pgtype.UUID `json:"candidate_id"`
	QuestionID         pgtype.UUID `json:"question_id"`
	QuestionRevisionID pgtype.UUID `json:"question_revision_id"`
	RoundNumber        int32       `json:"round_number"`
	ClientRequestID    pgtype.UUID `json:"client_request_id"`
}

type CreatePrivateRoundRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PairID             pgtype.UUID        `json:"pair_id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	MembershipEraID    pgtype.UUID        `json:"membership_era_id"`
	CandidateID        pgtype.UUID        `json:"candidate_id"`
	QuestionID         pgtype.UUID        `json:"question_id"`
	QuestionRevisionID pgtype.UUID        `json:"question_revision_id"`
	RoundNumber        int32              `json:"round_number"`
	Status             PrivateRoundStatus `json:"status"`
	AskedAt            pgtype.Timestamptz `json:"asked_at"`
	ClientRequestID    pgtype.UUID        `json:"client_request_id"`
}

func (q *Queries) CreatePrivateRound(ctx context.Context, arg CreatePrivateRoundParams) (CreatePrivateRoundRow, error) {
	row := q.db.QueryRow(ctx, createPrivateRound,
		arg.PairID,
		arg.ConversationID,
		arg.MembershipEraID,
		arg.CandidateID,
		arg.QuestionID,
		arg.QuestionRevisionID,
		arg.RoundNumber,
		arg.ClientRequestID,
	)
	var i CreatePrivateRoundRow
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.ConversationID,
		&i.MembershipEraID,
		&i.CandidateID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.RoundNumber,
		&i.Status,
		&i.AskedAt,
		&i.ClientRequestID,
	)
	return i, err
}

const getActivePrivateRoundForPair = `-- name: GetActivePrivateRoundForPair :one
SELECT id, pair_id, conversation_id, membership_era_id, candidate_id, question_id,
       question_revision_id, round_number, status, asked_at, client_request_id
FROM private_round
WHERE pair_id = $1
  AND membership_era_id = $2
  AND status = 'open'
ORDER BY asked_at DESC
LIMIT 1
`

type GetActivePrivateRoundForPairParams struct {
	PairID          pgtype.UUID `json:"pair_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
}

type GetActivePrivateRoundForPairRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PairID             pgtype.UUID        `json:"pair_id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	MembershipEraID    pgtype.UUID        `json:"membership_era_id"`
	CandidateID        pgtype.UUID        `json:"candidate_id"`
	QuestionID         pgtype.UUID        `json:"question_id"`
	QuestionRevisionID pgtype.UUID        `json:"question_revision_id"`
	RoundNumber        int32              `json:"round_number"`
	Status             PrivateRoundStatus `json:"status"`
	AskedAt            pgtype.Timestamptz `json:"asked_at"`
	ClientRequestID    pgtype.UUID        `json:"client_request_id"`
}

func (q *Queries) GetActivePrivateRoundForPair(ctx context.Context, arg GetActivePrivateRoundForPairParams) (GetActivePrivateRoundForPairRow, error) {
	row := q.db.QueryRow(ctx, getActivePrivateRoundForPair, arg.PairID, arg.MembershipEraID)
	var i GetActivePrivateRoundForPairRow
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.ConversationID,
		&i.MembershipEraID,
		&i.CandidateID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.RoundNumber,
		&i.Status,
		&i.AskedAt,
		&i.ClientRequestID,
	)
	return i, err
}

const getCreatorUnresolvedPrivateCandidate = `-- name: GetCreatorUnresolvedPrivateCandidate :one
SELECT c.id, candidate.conversation_id, c.category
FROM private_question_candidate AS candidate
JOIN private_conversation AS c ON c.id = candidate.conversation_id
WHERE c.pair_id = $1
  AND c.membership_era_id = $2
  AND c.created_by_participant_id = $3
  AND candidate.state = 'unresolved'
LIMIT 1
`

type GetCreatorUnresolvedPrivateCandidateParams struct {
	PairID          pgtype.UUID `json:"pair_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
	ParticipantID   pgtype.UUID `json:"participant_id"`
}

type GetCreatorUnresolvedPrivateCandidateRow struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	Category       string      `json:"category"`
}

func (q *Queries) GetCreatorUnresolvedPrivateCandidate(ctx context.Context, arg GetCreatorUnresolvedPrivateCandidateParams) (GetCreatorUnresolvedPrivateCandidateRow, error) {
	row := q.db.QueryRow(ctx, getCreatorUnresolvedPrivateCandidate, arg.PairID, arg.MembershipEraID, arg.ParticipantID)
	var i GetCreatorUnresolvedPrivateCandidateRow
	err := row.Scan(&i.ID, &i.ConversationID, &i.Category)
	return i, err
}

const getOpenPrivateRoundForConversation = `-- name: GetOpenPrivateRoundForConversation :one
SELECT round.id, round.pair_id, round.conversation_id, round.membership_era_id, round.candidate_id, round.question_id,
       round.question_revision_id, round.round_number, round.status, round.asked_at, round.client_request_id,
       r.text, r.category, r.intensity
FROM private_round AS round
JOIN question_revision AS r ON r.id = round.question_revision_id
WHERE round.pair_id = $1
  AND round.conversation_id = $2
  AND round.membership_era_id = $3
  AND round.status = 'open'
ORDER BY round.round_number DESC
LIMIT 1
`

type GetOpenPrivateRoundForConversationParams struct {
	PairID          pgtype.UUID `json:"pair_id"`
	ConversationID  pgtype.UUID `json:"conversation_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
}

type GetOpenPrivateRoundForConversationRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PairID             pgtype.UUID        `json:"pair_id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	MembershipEraID    pgtype.UUID        `json:"membership_era_id"`
	CandidateID        pgtype.UUID        `json:"candidate_id"`
	QuestionID         pgtype.UUID        `json:"question_id"`
	QuestionRevisionID pgtype.UUID        `json:"question_revision_id"`
	RoundNumber        int32              `json:"round_number"`
	Status             PrivateRoundStatus `json:"status"`
	AskedAt            pgtype.Timestamptz `json:"asked_at"`
	ClientRequestID    pgtype.UUID        `json:"client_request_id"`
	Text               string             `json:"text"`
	Category           string             `json:"category"`
	Intensity          string             `json:"intensity"`
}

func (q *Queries) GetOpenPrivateRoundForConversation(ctx context.Context, arg GetOpenPrivateRoundForConversationParams) (GetOpenPrivateRoundForConversationRow, error) {
	row := q.db.QueryRow(ctx, getOpenPrivateRoundForConversation, arg.PairID, arg.ConversationID, arg.MembershipEraID)
	var i GetOpenPrivateRoundForConversationRow
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.ConversationID,
		&i.MembershipEraID,
		&i.CandidateID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.RoundNumber,
		&i.Status,
		&i.AskedAt,
		&i.ClientRequestID,
		&i.Text,
		&i.Category,
		&i.Intensity,
	)
	return i, err
}

const getPrivateAnswerByMembership = `-- name: GetPrivateAnswerByMembership :one
SELECT id, round_id, membership_era_id, membership_id, participant_id, body, created_at
FROM private_answer
WHERE round_id = $1
  AND membership_id = $2
  AND membership_era_id = $3
`

type GetPrivateAnswerByMembershipParams struct {
	RoundID         pgtype.UUID `json:"round_id"`
	MembershipID    pgtype.UUID `json:"membership_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
}

func (q *Queries) GetPrivateAnswerByMembership(ctx context.Context, arg GetPrivateAnswerByMembershipParams) (PrivateAnswer, error) {
	row := q.db.QueryRow(ctx, getPrivateAnswerByMembership, arg.RoundID, arg.MembershipID, arg.MembershipEraID)
	var i PrivateAnswer
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.MembershipEraID,
		&i.MembershipID,
		&i.ParticipantID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getPrivateCandidateForUpdate = `-- name: GetPrivateCandidateForUpdate :one
SELECT c.id, c.conversation_id, c.question_id, c.question_revision_id, c.state,
       c.created_at, c.resolved_at, c.liked_at, c.skip_request_id,
       c.skip_result_candidate_id, r.text, r.category, r.intensity, r.withdrawn_at
FROM private_question_candidate AS c
JOIN question_revision AS r ON r.id = c.question_revision_id
WHERE c.id = $1
  AND c.conversation_id = $2
FOR UPDATE
`

type GetPrivateCandidateForUpdateParams struct {
	CandidateID    pgtype.UUID `json:"candidate_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

type GetPrivateCandidateForUpdateRow struct {
	ID                    pgtype.UUID                   `json:"id"`
	ConversationID        pgtype.UUID                   `json:"conversation_id"`
	QuestionID            pgtype.UUID                   `json:"question_id"`
	QuestionRevisionID    pgtype.UUID                   `json:"question_revision_id"`
	State                 PrivateQuestionCandidateState `json:"state"`
	CreatedAt             pgtype.Timestamptz            `json:"created_at"`
	ResolvedAt            pgtype.Timestamptz            `json:"resolved_at"`
	LikedAt               pgtype.Timestamptz            `json:"liked_at"`
	SkipRequestID         pgtype.UUID                   `json:"skip_request_id"`
	SkipResultCandidateID pgtype.UUID                   `json:"skip_result_candidate_id"`
	Text                  string                        `json:"text"`
	Category              string                        `json:"category"`
	Intensity             string                        `json:"intensity"`
	WithdrawnAt           pgtype.Timestamptz            `json:"withdrawn_at"`
}

func (q *Queries) GetPrivateCandidateForUpdate(ctx context.Context, arg GetPrivateCandidateForUpdateParams) (GetPrivateCandidateForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPrivateCandidateForUpdate, arg.CandidateID, arg.ConversationID)
	var i GetPrivateCandidateForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.State,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.LikedAt,
		&i.SkipRequestID,
		&i.SkipResultCandidateID,
		&i.Text,
		&i.Category,
		&i.Intensity,
		&i.WithdrawnAt,
	)
	return i, err
}

const getPrivateConversation = `-- name: GetPrivateConversation :one
SELECT c.id, c.pair_id, c.category, c.created_by_participant_id, c.membership_era_id,
       c.created_at, c.selection_seed, creator.display_name AS creator_display_name
FROM private_conversation AS c
JOIN participant AS creator ON creator.id = c.created_by_participant_id
WHERE c.id = $1
  AND c.pair_id = $2
  AND c.membership_era_id = $3
`

type GetPrivateConversationParams struct {
	ConversationID  pgtype.UUID `json:"conversation_id"`
	PairID          pgtype.UUID `json:"pair_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
}

type GetPrivateConversationRow struct {
	ID                     pgtype.UUID        `json:"id"`
	PairID                 pgtype.UUID        `json:"pair_id"`
	Category               string             `json:"category"`
	CreatedByParticipantID pgtype.UUID        `json:"created_by_participant_id"`
	MembershipEraID        pgtype.UUID        `json:"membership_era_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	SelectionSeed          string             `json:"selection_seed"`
	CreatorDisplayName     string             `json:"creator_display_name"`
}

func (q *Queries) GetPrivateConversation(ctx context.Context, arg GetPrivateConversationParams) (GetPrivateConversationRow, error) {
	row := q.db.QueryRow(ctx, getPrivateConversation, arg.ConversationID, arg.PairID, arg.MembershipEraID)
	var i GetPrivateConversationRow
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.Category,
		&i.CreatedByParticipantID,
		&i.MembershipEraID,
		&i.CreatedAt,
		&i.SelectionSeed,
		&i.CreatorDisplayName,
	)
	return i, err
}

const getPrivateConversationByKey = `-- name: GetPrivateConversationByKey :one
SELECT id, pair_id, category, created_by_participant_id, membership_era_id, created_at, selection_seed
FROM private_conversation
WHERE pair_id = $1
  AND membership_era_id = $2
  AND category = $3
`

type GetPrivateConversationByKeyParams struct {
	PairID          pgtype.UUID `json:"pair_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
	Category        string      `json:"category"`
}

func (q *Queries) GetPrivateConversationByKey(ctx context.Context, arg GetPrivateConversationByKeyParams) (PrivateConversation, error) {
	row := q.db.QueryRow(ctx, getPrivateConversationByKey, arg.PairID, arg.MembershipEraID, arg.Category)
	var i PrivateConversation
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.Category,
		&i.CreatedByParticipantID,
		&i.MembershipEraID,
		&i.CreatedAt,
		&i.SelectionSeed,
	)
	return i, err
}

const getPrivatePairAccess = `-- name: GetPrivatePairAccess :one
SELECT
    p.id AS pair_id,
    p.relationship_type,
    actor_membership.id AS actor_membership_id,
    other_membership.id AS other_membership_id,
    actor_membership.participant_id AS actor_participant_id,
    other_membership.participant_id AS other_participant_id,
    active_era.id AS membership_era_id
FROM pair AS p
JOIN pair_membership AS actor_membership
    ON actor_membership.pair_id = p.id
   AND actor_membership.participant_id = $1
   AND actor_membership.ended_at IS NULL
JOIN pair_membership AS other_membership
    ON other_membership.pair_id = p.id
   AND other_membership.slot <> actor_membership.slot
   AND other_membership.ended_at IS NULL
JOIN pair_membership_era AS active_era
    ON active_era.pair_id = p.id
   AND active_era.ended_at IS NULL
WHERE p.id = $2
  AND p.terminated_at IS NULL
`

type GetPrivatePairAccessParams struct {
	ParticipantID pgtype.UUID `json:"participant_id"`
	PairID        pgtype.UUID `json:"pair_id"`
}

type GetPrivatePairAccessRow struct {
	PairID             pgtype.UUID          `json:"pair_id"`
	RelationshipType   PairRelationshipType `json:"relationship_type"`
	ActorMembershipID  pgtype.UUID          `json:"actor_membership_id"`
	OtherMembershipID  pgtype.UUID          `json:"other_membership_id"`
	ActorParticipantID pgtype.UUID          `json:"actor_participant_id"`
	OtherParticipantID pgtype.UUID          `json:"other_participant_id"`
	MembershipEraID    pgtype.UUID          `json:"membership_era_id"`
}

func (q *Queries) GetPrivatePairAccess(ctx context.Context, arg GetPrivatePairAccessParams) (GetPrivatePairAccessRow, error) {
	row := q.db.QueryRow(ctx, getPrivatePairAccess, arg.ParticipantID, arg.PairID)
	var i GetPrivatePairAccessRow
	err := row.Scan(
		&i.PairID,
		&i.RelationshipType,
		&i.ActorMembershipID,
		&i.OtherMembershipID,
		&i.ActorParticipantID,
		&i.OtherParticipantID,
		&i.MembershipEraID,
	)
	return i, err
}

const getPrivateRoundByCandidate = `-- name: GetPrivateRoundByCandidate :one
SELECT round.id, round.pair_id, round.conversation_id, round.membership_era_id, round.candidate_id, round.question_id,
       round.question_revision_id, round.round_number, round.status, round.asked_at, round.client_request_id,
       r.text, r.category, r.intensity
FROM private_round AS round
JOIN question_revision AS r ON r.id = round.question_revision_id
WHERE round.candidate_id = $1
  AND round.conversation_id = $2
LIMIT 1
`

type GetPrivateRoundByCandidateParams struct {
	CandidateID    pgtype.UUID `json:"candidate_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

type GetPrivateRoundByCandidateRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PairID             pgtype.UUID        `json:"pair_id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	MembershipEraID    pgtype.UUID        `json:"membership_era_id"`
	CandidateID        pgtype.UUID        `json:"candidate_id"`
	QuestionID         pgtype.UUID        `json:"question_id"`
	QuestionRevisionID pgtype.UUID        `json:"question_revision_id"`
	RoundNumber        int32              `json:"round_number"`
	Status             PrivateRoundStatus `json:"status"`
	AskedAt            pgtype.Timestamptz `json:"asked_at"`
	ClientRequestID    pgtype.UUID        `json:"client_request_id"`
	Text               string             `json:"text"`
	Category           string             `json:"category"`
	Intensity          string             `json:"intensity"`
}

func (q *Queries) GetPrivateRoundByCandidate(ctx context.Context, arg GetPrivateRoundByCandidateParams) (GetPrivateRoundByCandidateRow, error) {
	row := q.db.QueryRow(ctx, getPrivateRoundByCandidate, arg.CandidateID, arg.ConversationID)
	var i GetPrivateRoundByCandidateRow
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.ConversationID,
		&i.MembershipEraID,
		&i.CandidateID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.RoundNumber,
		&i.Status,
		&i.AskedAt,
		&i.ClientRequestID,
		&i.Text,
		&i.Category,
		&i.Intensity,
	)
	return i, err
}

const getPrivateRoundForParticipant = `-- name: GetPrivateRoundForParticipant :one
SELECT round.id, round.pair_id, round.conversation_id, round.membership_era_id,
       round.candidate_id, round.question_id, round.question_revision_id,
       round.round_number, round.status, round.asked_at, round.client_request_id,
       round.declined_by_membership_id, round.declined_at,
       r.text, r.category, r.intensity
FROM private_round AS round
JOIN question_revision AS r ON r.id = round.question_revision_id
WHERE round.id = $1
  AND round.pair_id = $2
  AND round.membership_era_id = $3
`

type GetPrivateRoundForParticipantParams struct {
	RoundID         pgtype.UUID `json:"round_id"`
	PairID          pgtype.UUID `json:"pair_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
}

type GetPrivateRoundForParticipantRow struct {
	ID                     pgtype.UUID        `json:"id"`
	PairID                 pgtype.UUID        `json:"pair_id"`
	ConversationID         pgtype.UUID        `json:"conversation_id"`
	MembershipEraID        pgtype.UUID        `json:"membership_era_id"`
	CandidateID            pgtype.UUID        `json:"candidate_id"`
	QuestionID             pgtype.UUID        `json:"question_id"`
	QuestionRevisionID     pgtype.UUID        `json:"question_revision_id"`
	RoundNumber            int32              `json:"round_number"`
	Status                 PrivateRoundStatus `json:"status"`
	AskedAt                pgtype.Timestamptz `json:"asked_at"`
	ClientRequestID        pgtype.UUID        `json:"client_request_id"`
	DeclinedByMembershipID pgtype.UUID        `json:"declined_by_membership_id"`
	DeclinedAt             pgtype.Timestamptz `json:"declined_at"`
	Text                   string             `json:"text"`
	Category               string             `json:"category"`
	Intensity              string             `json:"intensity"`
}

func (q *Queries) GetPrivateRoundForParticipant(ctx context.Context, arg GetPrivateRoundForParticipantParams) (GetPrivateRoundForParticipantRow, error) {
	row := q.db.QueryRow(ctx, getPrivateRoundForParticipant, arg.RoundID, arg.PairID, arg.MembershipEraID)
	var i GetPrivateRoundForParticipantRow
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.ConversationID,
		&i.MembershipEraID,
		&i.CandidateID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.RoundNumber,
		&i.Status,
		&i.AskedAt,
		&i.ClientRequestID,
		&i.DeclinedByMembershipID,
		&i.DeclinedAt,
		&i.Text,
		&i.Category,
		&i.Intensity,
	)
	return i, err
}

const getSkippedPrivateCandidateByRequest = `-- name: GetSkippedPrivateCandidateByRequest :one
SELECT id, conversation_id, skip_result_candidate_id
FROM private_question_candidate
WHERE conversation_id = $1
  AND skip_request_id = $2
LIMIT 1
`

type GetSkippedPrivateCandidateByRequestParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	SkipRequestID  pgtype.UUID `json:"skip_request_id"`
}

type GetSkippedPrivateCandidateByRequestRow struct {
	ID                    pgtype.UUID `json:"id"`
	ConversationID        pgtype.UUID `json:"conversation_id"`
	SkipResultCandidateID pgtype.UUID `json:"skip_result_candidate_id"`
}

func (q *Queries) GetSkippedPrivateCandidateByRequest(ctx context.Context, arg GetSkippedPrivateCandidateByRequestParams) (GetSkippedPrivateCandidateByRequestRow, error) {
	row := q.db.QueryRow(ctx, getSkippedPrivateCandidateByRequest, arg.ConversationID, arg.SkipRequestID)
	var i GetSkippedPrivateCandidateByRequestRow
	err := row.Scan(&i.ID, &i.ConversationID, &i.SkipResultCandidateID)
	return i, err
}

const getUnresolvedPrivateCandidate = `-- name: GetUnresolvedPrivateCandidate :one
SELECT c.id, c.conversation_id, c.question_id, c.question_revision_id, c.state,
       c.created_at, c.resolved_at, c.liked_at, r.text, r.category, r.intensity,
       r.withdrawn_at
FROM private_question_candidate AS c
JOIN question_revision AS r ON r.id = c.question_revision_id
WHERE c.conversation_id = $1
  AND c.state = 'unresolved'
LIMIT 1
`

type GetUnresolvedPrivateCandidateRow struct {
	ID                 pgtype.UUID                   `json:"id"`
	ConversationID     pgtype.UUID                   `json:"conversation_id"`
	QuestionID         pgtype.UUID                   `json:"question_id"`
	QuestionRevisionID pgtype.UUID                   `json:"question_revision_id"`
	State              PrivateQuestionCandidateState `json:"state"`
	CreatedAt          pgtype.Timestamptz            `json:"created_at"`
	ResolvedAt         pgtype.Timestamptz            `json:"resolved_at"`
	LikedAt            pgtype.Timestamptz            `json:"liked_at"`
	Text               string                        `json:"text"`
	Category           string                        `json:"category"`
	Intensity          string                        `json:"intensity"`
	WithdrawnAt        pgtype.Timestamptz            `json:"withdrawn_at"`
}

func (q *Queries) GetUnresolvedPrivateCandidate(ctx context.Context, conversationID pgtype.UUID) (GetUnresolvedPrivateCandidateRow, error) {
	row := q.db.QueryRow(ctx, getUnresolvedPrivateCandidate, conversationID)
	var i GetUnresolvedPrivateCandidateRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.State,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.LikedAt,
		&i.Text,
		&i.Category,
		&i.Intensity,
		&i.WithdrawnAt,
	)
	return i, err
}

const invalidatePrivateCandidate = `-- name: InvalidatePrivateCandidate :exec
UPDATE private_question_candidate
SET state = 'invalidated', resolved_at = COALESCE(resolved_at, now())
WHERE id = $1 AND state = 'unresolved'
`

func (q *Queries) InvalidatePrivateCandidate(ctx context.Context, candidateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidatePrivateCandidate, candidateID)
	return err
}

const invalidatePrivateCandidatesForRevision = `-- name: InvalidatePrivateCandidatesForRevision :exec
UPDATE private_question_candidate
SET state = 'invalidated', resolved_at = COALESCE(resolved_at, now())
WHERE question_revision_id = $1 AND state = 'unresolved'
`

func (q *Queries) InvalidatePrivateCandidatesForRevision(ctx context.Context, questionRevisionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidatePrivateCandidatesForRevision, questionRevisionID)
	return err
}

const listConsumedPrivateQuestionIDs = `-- name: ListConsumedPrivateQuestionIDs :many
SELECT question_id FROM private_question_candidate
WHERE conversation_id = $1 AND state IN ('asked', 'skipped')
`

func (q *Queries) ListConsumedPrivateQuestionIDs(ctx context.Context, conversationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listConsumedPrivateQuestionIDs, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var question_id pgtype.UUID
		if err := rows.Scan(&question_id); err != nil {
			return nil, err
		}
		items = append(items, question_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligiblePrivateQuestions = `-- name: ListEligiblePrivateQuestions :many
SELECT q.id, r.id AS question_revision_id, r.text, r.category, r.intensity
FROM question AS q
JOIN question_revision AS r ON r.id = q.current_revision_id
WHERE q.is_active = true
  AND r.category = $1
  AND r.relationship_fit IN ('both', $2)
  AND r.mode_fit IN ('both', 'private')
  AND r.withdrawn_at IS NULL
ORDER BY q.id
`

type ListEligiblePrivateQuestionsParams struct {
	Category         string `json:"category"`
	RelationshipType string `json:"relationship_type"`
}

type ListEligiblePrivateQuestionsRow struct {
	ID                 pgtype.UUID `json:"id"`
	QuestionRevisionID pgtype.UUID `json:"question_revision_id"`
	Text               string      `json:"text"`
	Category           string      `json:"category"`
	Intensity          string      `json:"intensity"`
}

func (q *Queries) ListEligiblePrivateQuestions(ctx context.Context, arg ListEligiblePrivateQuestionsParams) ([]ListEligiblePrivateQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listEligiblePrivateQuestions, arg.Category, arg.RelationshipType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligiblePrivateQuestionsRow
	for rows.Next() {
		var i ListEligiblePrivateQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionRevisionID,
			&i.Text,
			&i.Category,
			&i.Intensity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivateAnswers = `-- name: ListPrivateAnswers :many
SELECT id, round_id, membership_era_id, membership_id, participant_id, body, created_at
FROM private_answer
WHERE round_id = $1
  AND membership_era_id = $2
ORDER BY created_at, id
`

type ListPrivateAnswersParams struct {
	RoundID         pgtype.UUID `json:"round_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
}

func (q *Queries) ListPrivateAnswers(ctx context.Context, arg ListPrivateAnswersParams) ([]PrivateAnswer, error) {
	rows, err := q.db.Query(ctx, listPrivateAnswers, arg.RoundID, arg.MembershipEraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivateAnswer
	for rows.Next() {
		var i PrivateAnswer
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.MembershipEraID,
			&i.MembershipID,
			&i.ParticipantID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivateRevealViews = `-- name: ListPrivateRevealViews :many
SELECT id, round_id, membership_era_id, membership_id, participant_id, viewed_at
FROM private_reveal_view
WHERE round_id = $1
  AND membership_era_id = $2
ORDER BY viewed_at, id
`

type ListPrivateRevealViewsParams struct {
	RoundID         pgtype.UUID `json:"round_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
}

func (q *Queries) ListPrivateRevealViews(ctx context.Context, arg ListPrivateRevealViewsParams) ([]PrivateRevealView, error) {
	rows, err := q.db.Query(ctx, listPrivateRevealViews, arg.RoundID, arg.MembershipEraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivateRevealView
	for rows.Next() {
		var i PrivateRevealView
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.MembershipEraID,
			&i.MembershipID,
			&i.ParticipantID,
			&i.ViewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPrivatePair = `-- name: LockPrivatePair :one
SELECT id FROM pair WHERE id = $1 AND terminated_at IS NULL FOR UPDATE
`

func (q *Queries) LockPrivatePair(ctx context.Context, pairID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockPrivatePair, pairID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markPrivateCandidateAsked = `-- name: MarkPrivateCandidateAsked :one
UPDATE private_question_candidate
SET state = 'asked', resolved_at = now()
WHERE id = $1
  AND conversation_id = $2
  AND state = 'unresolved'
RETURNING id
`

type MarkPrivateCandidateAskedParams struct {
	CandidateID    pgtype.UUID `json:"candidate_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) MarkPrivateCandidateAsked(ctx context.Context, arg MarkPrivateCandidateAskedParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markPrivateCandidateAsked, arg.CandidateID, arg.ConversationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markPrivateCandidateSkipped = `-- name: MarkPrivateCandidateSkipped :one
UPDATE private_question_candidate
SET state = 'skipped', resolved_at = now(), skip_request_id = $1
WHERE id = $2
  AND conversation_id = $3
  AND state = 'unresolved'
RETURNING id
`

type MarkPrivateCandidateSkippedParams struct {
	SkipRequestID  pgtype.UUID `json:"skip_request_id"`
	CandidateID    pgtype.UUID `json:"candidate_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) MarkPrivateCandidateSkipped(ctx context.Context, arg MarkPrivateCandidateSkippedParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markPrivateCandidateSkipped, arg.SkipRequestID, arg.CandidateID, arg.ConversationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const nextPrivateRoundNumber = `-- name: NextPrivateRoundNumber :one
SELECT (COALESCE(MAX(round_number), 0) + 1)::integer AS round_number
FROM private_round
WHERE conversation_id = $1
`

func (q *Queries) NextPrivateRoundNumber(ctx context.Context, conversationID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextPrivateRoundNumber, conversationID)
	var round_number int32
	err := row.Scan(&round_number)
	return round_number, err
}

const retirePrivateRound = `-- name: RetirePrivateRound :one
UPDATE private_round
SET status = 'retired', declined_by_membership_id = $1, declined_at = now()
WHERE id = $2
  AND pair_id = $3
  AND membership_era_id = $4
  AND status = 'open'
RETURNING id
`

type RetirePrivateRoundParams struct {
	MembershipID    pgtype.UUID `json:"membership_id"`
	RoundID         pgtype.UUID `json:"round_id"`
	PairID          pgtype.UUID `json:"pair_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
}

func (q *Queries) RetirePrivateRound(ctx context.Context, arg RetirePrivateRoundParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, retirePrivateRound,
		arg.MembershipID,
		arg.RoundID,
		arg.PairID,
		arg.MembershipEraID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const setPrivateCandidateLike = `-- name: SetPrivateCandidateLike :one
UPDATE private_question_candidate
SET liked_at = CASE WHEN $1::boolean THEN now() ELSE NULL END
WHERE id = $2
  AND conversation_id = $3
  AND state = 'unresolved'
RETURNING liked_at
`

type SetPrivateCandidateLikeParams struct {
	Liked          bool        `json:"liked"`
	CandidateID    pgtype.UUID `json:"candidate_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) SetPrivateCandidateLike(ctx context.Context, arg SetPrivateCandidateLikeParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, setPrivateCandidateLike, arg.Liked, arg.CandidateID, arg.ConversationID)
	var liked_at pgtype.Timestamptz
	err := row.Scan(&liked_at)
	return liked_at, err
}

const setPrivateCandidateSkipResult = `-- name: SetPrivateCandidateSkipResult :exec
UPDATE private_question_candidate
SET skip_result_candidate_id = $1
WHERE id = $2
  AND state = 'skipped'
`

type SetPrivateCandidateSkipResultParams struct {
	SkipResultCandidateID pgtype.UUID `json:"skip_result_candidate_id"`
	CandidateID           pgtype.UUID `json:"candidate_id"`
}

func (q *Queries) SetPrivateCandidateSkipResult(ctx context.Context, arg SetPrivateCandidateSkipResultParams) error {
	_, err := q.db.Exec(ctx, setPrivateCandidateSkipResult, arg.SkipResultCandidateID, arg.CandidateID)
	return err
}
