// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: private.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrivateConversation = `-- name: CreatePrivateConversation :one
INSERT INTO private_conversation (pair_id, category, created_by_participant_id, membership_era_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (pair_id, membership_era_id, category) DO NOTHING
RETURNING id, pair_id, category, created_by_participant_id, membership_era_id, created_at, selection_seed
`

type CreatePrivateConversationParams struct {
	PairID                 pgtype.UUID `json:"pair_id"`
	Category               string      `json:"category"`
	CreatedByParticipantID pgtype.UUID `json:"created_by_participant_id"`
	MembershipEraID        pgtype.UUID `json:"membership_era_id"`
}

func (q *Queries) CreatePrivateConversation(ctx context.Context, arg CreatePrivateConversationParams) (PrivateConversation, error) {
	row := q.db.QueryRow(ctx, createPrivateConversation,
		arg.PairID,
		arg.Category,
		arg.CreatedByParticipantID,
		arg.MembershipEraID,
	)
	var i PrivateConversation
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.Category,
		&i.CreatedByParticipantID,
		&i.MembershipEraID,
		&i.CreatedAt,
		&i.SelectionSeed,
	)
	return i, err
}

const createPrivateQuestionCandidate = `-- name: CreatePrivateQuestionCandidate :one
INSERT INTO private_question_candidate (conversation_id, question_id, question_revision_id)
VALUES ($1, $2, $3)
ON CONFLICT (conversation_id) WHERE state = 'unresolved' DO NOTHING
RETURNING id, conversation_id, question_id, question_revision_id, state, created_at, resolved_at
`

type CreatePrivateQuestionCandidateParams struct {
	ConversationID     pgtype.UUID `json:"conversation_id"`
	QuestionID         pgtype.UUID `json:"question_id"`
	QuestionRevisionID pgtype.UUID `json:"question_revision_id"`
}

func (q *Queries) CreatePrivateQuestionCandidate(ctx context.Context, arg CreatePrivateQuestionCandidateParams) (PrivateQuestionCandidate, error) {
	row := q.db.QueryRow(ctx, createPrivateQuestionCandidate, arg.ConversationID, arg.QuestionID, arg.QuestionRevisionID)
	var i PrivateQuestionCandidate
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.State,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getPrivateConversation = `-- name: GetPrivateConversation :one
SELECT c.id, c.pair_id, c.category, c.created_by_participant_id, c.membership_era_id,
       c.created_at, c.selection_seed, creator.display_name AS creator_display_name
FROM private_conversation AS c
JOIN participant AS creator ON creator.id = c.created_by_participant_id
WHERE c.id = $1
  AND c.pair_id = $2
  AND c.membership_era_id = $3
`

type GetPrivateConversationParams struct {
	ConversationID  pgtype.UUID `json:"conversation_id"`
	PairID          pgtype.UUID `json:"pair_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
}

type GetPrivateConversationRow struct {
	ID                     pgtype.UUID        `json:"id"`
	PairID                 pgtype.UUID        `json:"pair_id"`
	Category               string             `json:"category"`
	CreatedByParticipantID pgtype.UUID        `json:"created_by_participant_id"`
	MembershipEraID        pgtype.UUID        `json:"membership_era_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	SelectionSeed          string             `json:"selection_seed"`
	CreatorDisplayName     string             `json:"creator_display_name"`
}

func (q *Queries) GetPrivateConversation(ctx context.Context, arg GetPrivateConversationParams) (GetPrivateConversationRow, error) {
	row := q.db.QueryRow(ctx, getPrivateConversation, arg.ConversationID, arg.PairID, arg.MembershipEraID)
	var i GetPrivateConversationRow
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.Category,
		&i.CreatedByParticipantID,
		&i.MembershipEraID,
		&i.CreatedAt,
		&i.SelectionSeed,
		&i.CreatorDisplayName,
	)
	return i, err
}

const getPrivateConversationByKey = `-- name: GetPrivateConversationByKey :one
SELECT id, pair_id, category, created_by_participant_id, membership_era_id, created_at, selection_seed
FROM private_conversation
WHERE pair_id = $1
  AND membership_era_id = $2
  AND category = $3
`

type GetPrivateConversationByKeyParams struct {
	PairID          pgtype.UUID `json:"pair_id"`
	MembershipEraID pgtype.UUID `json:"membership_era_id"`
	Category        string      `json:"category"`
}

func (q *Queries) GetPrivateConversationByKey(ctx context.Context, arg GetPrivateConversationByKeyParams) (PrivateConversation, error) {
	row := q.db.QueryRow(ctx, getPrivateConversationByKey, arg.PairID, arg.MembershipEraID, arg.Category)
	var i PrivateConversation
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.Category,
		&i.CreatedByParticipantID,
		&i.MembershipEraID,
		&i.CreatedAt,
		&i.SelectionSeed,
	)
	return i, err
}

const getPrivatePairAccess = `-- name: GetPrivatePairAccess :one
SELECT
    p.id AS pair_id,
    p.relationship_type,
    actor_membership.id AS actor_membership_id,
    actor_membership.participant_id AS actor_participant_id,
    other_membership.participant_id AS other_participant_id,
    active_era.id AS membership_era_id
FROM pair AS p
JOIN pair_membership AS actor_membership
    ON actor_membership.pair_id = p.id
   AND actor_membership.participant_id = $1
   AND actor_membership.ended_at IS NULL
JOIN pair_membership AS other_membership
    ON other_membership.pair_id = p.id
   AND other_membership.slot <> actor_membership.slot
   AND other_membership.ended_at IS NULL
JOIN pair_membership_era AS active_era
    ON active_era.pair_id = p.id
   AND active_era.ended_at IS NULL
WHERE p.id = $2
  AND p.terminated_at IS NULL
`

type GetPrivatePairAccessParams struct {
	ParticipantID pgtype.UUID `json:"participant_id"`
	PairID        pgtype.UUID `json:"pair_id"`
}

type GetPrivatePairAccessRow struct {
	PairID             pgtype.UUID          `json:"pair_id"`
	RelationshipType   PairRelationshipType `json:"relationship_type"`
	ActorMembershipID  pgtype.UUID          `json:"actor_membership_id"`
	ActorParticipantID pgtype.UUID          `json:"actor_participant_id"`
	OtherParticipantID pgtype.UUID          `json:"other_participant_id"`
	MembershipEraID    pgtype.UUID          `json:"membership_era_id"`
}

func (q *Queries) GetPrivatePairAccess(ctx context.Context, arg GetPrivatePairAccessParams) (GetPrivatePairAccessRow, error) {
	row := q.db.QueryRow(ctx, getPrivatePairAccess, arg.ParticipantID, arg.PairID)
	var i GetPrivatePairAccessRow
	err := row.Scan(
		&i.PairID,
		&i.RelationshipType,
		&i.ActorMembershipID,
		&i.ActorParticipantID,
		&i.OtherParticipantID,
		&i.MembershipEraID,
	)
	return i, err
}

const getUnresolvedPrivateCandidate = `-- name: GetUnresolvedPrivateCandidate :one
SELECT c.id, c.conversation_id, c.question_id, c.question_revision_id, c.state,
       c.created_at, c.resolved_at, r.text, r.category, r.intensity
FROM private_question_candidate AS c
JOIN question_revision AS r ON r.id = c.question_revision_id
WHERE c.conversation_id = $1
  AND c.state = 'unresolved'
LIMIT 1
`

type GetUnresolvedPrivateCandidateRow struct {
	ID                 pgtype.UUID                   `json:"id"`
	ConversationID     pgtype.UUID                   `json:"conversation_id"`
	QuestionID         pgtype.UUID                   `json:"question_id"`
	QuestionRevisionID pgtype.UUID                   `json:"question_revision_id"`
	State              PrivateQuestionCandidateState `json:"state"`
	CreatedAt          pgtype.Timestamptz            `json:"created_at"`
	ResolvedAt         pgtype.Timestamptz            `json:"resolved_at"`
	Text               string                        `json:"text"`
	Category           string                        `json:"category"`
	Intensity          string                        `json:"intensity"`
}

func (q *Queries) GetUnresolvedPrivateCandidate(ctx context.Context, conversationID pgtype.UUID) (GetUnresolvedPrivateCandidateRow, error) {
	row := q.db.QueryRow(ctx, getUnresolvedPrivateCandidate, conversationID)
	var i GetUnresolvedPrivateCandidateRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.State,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.Text,
		&i.Category,
		&i.Intensity,
	)
	return i, err
}

const invalidatePrivateCandidatesForRevision = `-- name: InvalidatePrivateCandidatesForRevision :exec
UPDATE private_question_candidate
SET state = 'invalidated', resolved_at = COALESCE(resolved_at, now())
WHERE question_revision_id = $1 AND state = 'unresolved'
`

func (q *Queries) InvalidatePrivateCandidatesForRevision(ctx context.Context, questionRevisionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidatePrivateCandidatesForRevision, questionRevisionID)
	return err
}

const listConsumedPrivateQuestionIDs = `-- name: ListConsumedPrivateQuestionIDs :many
SELECT question_id FROM private_question_candidate
WHERE conversation_id = $1 AND state IN ('asked', 'skipped')
`

func (q *Queries) ListConsumedPrivateQuestionIDs(ctx context.Context, conversationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listConsumedPrivateQuestionIDs, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var question_id pgtype.UUID
		if err := rows.Scan(&question_id); err != nil {
			return nil, err
		}
		items = append(items, question_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligiblePrivateQuestions = `-- name: ListEligiblePrivateQuestions :many
SELECT q.id, r.id AS question_revision_id, r.text, r.category, r.intensity
FROM question AS q
JOIN question_revision AS r ON r.id = q.current_revision_id
WHERE q.is_active = true
  AND r.category = $1
  AND r.relationship_fit IN ('both', $2)
  AND r.mode_fit IN ('both', 'private')
  AND r.withdrawn_at IS NULL
ORDER BY q.id
`

type ListEligiblePrivateQuestionsParams struct {
	Category         string `json:"category"`
	RelationshipType string `json:"relationship_type"`
}

type ListEligiblePrivateQuestionsRow struct {
	ID                 pgtype.UUID `json:"id"`
	QuestionRevisionID pgtype.UUID `json:"question_revision_id"`
	Text               string      `json:"text"`
	Category           string      `json:"category"`
	Intensity          string      `json:"intensity"`
}

func (q *Queries) ListEligiblePrivateQuestions(ctx context.Context, arg ListEligiblePrivateQuestionsParams) ([]ListEligiblePrivateQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listEligiblePrivateQuestions, arg.Category, arg.RelationshipType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligiblePrivateQuestionsRow
	for rows.Next() {
		var i ListEligiblePrivateQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionRevisionID,
			&i.Text,
			&i.Category,
			&i.Intensity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPrivatePair = `-- name: LockPrivatePair :one
SELECT id FROM pair WHERE id = $1 AND terminated_at IS NULL FOR UPDATE
`

func (q *Queries) LockPrivatePair(ctx context.Context, pairID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockPrivatePair, pairID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
