// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	// Infrastructure-only query used by the test-database guard and transaction
	// smoke tests. Domain query files belong to their owning tickets.
	CurrentDatabase(ctx context.Context) (string, error)
	GetLocalTestValue(ctx context.Context) (string, error)
	SetLocalTestValue(ctx context.Context, value string) (string, error)
}

var _ Querier = (*Queries)(nil)
