// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error
	CreateAuthCredential(ctx context.Context, arg CreateAuthCredentialParams) error
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	CreateAuthSessionForEnabledAdminUser(ctx context.Context, arg CreateAuthSessionForEnabledAdminUserParams) (int64, error)
	CreateAuthSessionForEnabledRegisteredUser(ctx context.Context, arg CreateAuthSessionForEnabledRegisteredUserParams) (int64, error)
	CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error)
	CreateCreatorMembership(ctx context.Context, arg CreateCreatorMembershipParams) (PairMembership, error)
	CreatePair(ctx context.Context, arg CreatePairParams) (Pair, error)
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error)
	CreateRegisteredAuthUser(ctx context.Context, arg CreateRegisteredAuthUserParams) (AuthUser, error)
	// Infrastructure-only query used by the test-database guard and transaction
	// smoke tests. Domain query files belong to their owning tickets.
	CurrentDatabase(ctx context.Context) (string, error)
	DeleteExpiredAuthSessions(ctx context.Context, arg DeleteExpiredAuthSessionsParams) (int64, error)
	DeleteOldAuthRateLimits(ctx context.Context, dollar_1 interface{}) (int64, error)
	FindFormerTerminatedPair(ctx context.Context, arg FindFormerTerminatedPairParams) (pgtype.UUID, error)
	GetActivePairAccess(ctx context.Context, arg GetActivePairAccessParams) (GetActivePairAccessRow, error)
	GetAdminCredentialByEmail(ctx context.Context, emailNormalized string) (GetAdminCredentialByEmailRow, error)
	GetAuthSessionActor(ctx context.Context, arg GetAuthSessionActorParams) (GetAuthSessionActorRow, error)
	GetCreatedPairByRequestAndParticipant(ctx context.Context, arg GetCreatedPairByRequestAndParticipantParams) (Pair, error)
	GetCredentialByEmail(ctx context.Context, emailNormalized string) (GetCredentialByEmailRow, error)
	GetLocalTestValue(ctx context.Context) (string, error)
	GetParticipantByAuthUserID(ctx context.Context, authUserID pgtype.UUID) (Participant, error)
	GetParticipantByID(ctx context.Context, id pgtype.UUID) (Participant, error)
	HasActiveSecondSlot(ctx context.Context, pairID pgtype.UUID) (bool, error)
	HasAdminUser(ctx context.Context, authUserID pgtype.UUID) (bool, error)
	HasAuthSession(ctx context.Context, tokenHash []byte) (bool, error)
	IsAdminAuthUser(ctx context.Context, id pgtype.UUID) (bool, error)
	ListActivePairMembers(ctx context.Context, pairID pgtype.UUID) ([]ListActivePairMembersRow, error)
	ListAuthSessionTokenHashes(ctx context.Context, authUserID pgtype.UUID) ([][]byte, error)
	ListParticipantSpaces(ctx context.Context, participantID pgtype.UUID) ([]ListParticipantSpacesRow, error)
	LockActivePair(ctx context.Context, pairID pgtype.UUID) (pgtype.UUID, error)
	LockAdminBootstrapEmail(ctx context.Context, hashtextextended string) error
	LockAdminByEmailForRecovery(ctx context.Context, emailNormalized string) (pgtype.UUID, error)
	LockAuthUserForUpgrade(ctx context.Context, id pgtype.UUID) (AuthUser, error)
	ParticipantExists(ctx context.Context, participantID pgtype.UUID) (bool, error)
	ParticipantHasActiveMembership(ctx context.Context, arg ParticipantHasActiveMembershipParams) (bool, error)
	RenewAuthSession(ctx context.Context, arg RenewAuthSessionParams) (pgtype.Timestamptz, error)
	RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error)
	RevokeAuthSessionByTokenHash(ctx context.Context, arg RevokeAuthSessionByTokenHashParams) (int64, error)
	RevokeAuthSessionsForUser(ctx context.Context, arg RevokeAuthSessionsForUserParams) (int64, error)
	SetLocalTestValue(ctx context.Context, value string) (string, error)
	UpdateAuthCredentialPasswordHash(ctx context.Context, arg UpdateAuthCredentialPasswordHashParams) error
	UpdateIntendedPersonName(ctx context.Context, arg UpdateIntendedPersonNameParams) (Pair, error)
	UpgradeAnonymousAuthUser(ctx context.Context, id pgtype.UUID) (int64, error)
	UpsertAdminLoginRateLimit(ctx context.Context, subject string) (UpsertAdminLoginRateLimitRow, error)
	UpsertAuthRateLimit(ctx context.Context, arg UpsertAuthRateLimitParams) (UpsertAuthRateLimitRow, error)
}

var _ Querier = (*Queries)(nil)
