// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: question.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addQuestionLifecycleEvent = `-- name: AddQuestionLifecycleEvent :exec
INSERT INTO question_lifecycle_event (question_id, revision_id, action, admin_user_id, reason) VALUES ($1, $2, $3, $4, $5)
`

type AddQuestionLifecycleEventParams struct {
	QuestionID  pgtype.UUID `json:"question_id"`
	RevisionID  pgtype.UUID `json:"revision_id"`
	Action      string      `json:"action"`
	AdminUserID pgtype.UUID `json:"admin_user_id"`
	Reason      pgtype.Text `json:"reason"`
}

func (q *Queries) AddQuestionLifecycleEvent(ctx context.Context, arg AddQuestionLifecycleEventParams) error {
	_, err := q.db.Exec(ctx, addQuestionLifecycleEvent,
		arg.QuestionID,
		arg.RevisionID,
		arg.Action,
		arg.AdminUserID,
		arg.Reason,
	)
	return err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO question (is_active) VALUES (false) RETURNING id, current_revision_id, is_active, created_at
`

func (q *Queries) CreateQuestion(ctx context.Context) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CurrentRevisionID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createQuestionRevision = `-- name: CreateQuestionRevision :one
INSERT INTO question_revision (question_id, text, category, relationship_fit, mode_fit, intensity, revision_number, created_by_admin_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, question_id, text, category, relationship_fit, mode_fit, intensity, revision_number, created_by_admin_user_id, withdrawn_at, withdrawn_reason, withdrawn_by_admin_user_id, created_at
`

type CreateQuestionRevisionParams struct {
	QuestionID           pgtype.UUID `json:"question_id"`
	Text                 string      `json:"text"`
	Category             string      `json:"category"`
	RelationshipFit      string      `json:"relationship_fit"`
	ModeFit              string      `json:"mode_fit"`
	Intensity            string      `json:"intensity"`
	RevisionNumber       int32       `json:"revision_number"`
	CreatedByAdminUserID pgtype.UUID `json:"created_by_admin_user_id"`
}

func (q *Queries) CreateQuestionRevision(ctx context.Context, arg CreateQuestionRevisionParams) (QuestionRevision, error) {
	row := q.db.QueryRow(ctx, createQuestionRevision,
		arg.QuestionID,
		arg.Text,
		arg.Category,
		arg.RelationshipFit,
		arg.ModeFit,
		arg.Intensity,
		arg.RevisionNumber,
		arg.CreatedByAdminUserID,
	)
	var i QuestionRevision
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.Category,
		&i.RelationshipFit,
		&i.ModeFit,
		&i.Intensity,
		&i.RevisionNumber,
		&i.CreatedByAdminUserID,
		&i.WithdrawnAt,
		&i.WithdrawnReason,
		&i.WithdrawnByAdminUserID,
		&i.CreatedAt,
	)
	return i, err
}

const findQuestionDuplicates = `-- name: FindQuestionDuplicates :many
SELECT q.id, r.text, r.revision_number, q.is_active
FROM question q JOIN question_revision r ON r.id = q.current_revision_id
WHERE lower(btrim(regexp_replace(r.text, '[[:space:]]+', ' ', 'g')))
    = lower(btrim(regexp_replace($1, '[[:space:]]+', ' ', 'g')))
  AND ($2::text = '' OR q.id::text <> $2::text)
ORDER BY q.created_at, q.id
`

type FindQuestionDuplicatesParams struct {
	Text              string `json:"text"`
	ExcludeQuestionID string `json:"exclude_question_id"`
}

type FindQuestionDuplicatesRow struct {
	ID             pgtype.UUID `json:"id"`
	Text           string      `json:"text"`
	RevisionNumber int32       `json:"revision_number"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) FindQuestionDuplicates(ctx context.Context, arg FindQuestionDuplicatesParams) ([]FindQuestionDuplicatesRow, error) {
	rows, err := q.db.Query(ctx, findQuestionDuplicates, arg.Text, arg.ExcludeQuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindQuestionDuplicatesRow
	for rows.Next() {
		var i FindQuestionDuplicatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.RevisionNumber,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestion = `-- name: GetQuestion :one
SELECT q.id, q.current_revision_id, q.is_active, q.created_at,
       r.id AS revision_id, r.text, r.category, r.relationship_fit, r.mode_fit,
       r.intensity, r.revision_number, r.created_at AS revision_created_at,
       r.withdrawn_at, r.withdrawn_reason, r.created_by_admin_user_id
FROM question q JOIN question_revision r ON r.id = q.current_revision_id
WHERE q.id = $1
`

type GetQuestionRow struct {
	ID                   pgtype.UUID        `json:"id"`
	CurrentRevisionID    pgtype.UUID        `json:"current_revision_id"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	RevisionID           pgtype.UUID        `json:"revision_id"`
	Text                 string             `json:"text"`
	Category             string             `json:"category"`
	RelationshipFit      string             `json:"relationship_fit"`
	ModeFit              string             `json:"mode_fit"`
	Intensity            string             `json:"intensity"`
	RevisionNumber       int32              `json:"revision_number"`
	RevisionCreatedAt    pgtype.Timestamptz `json:"revision_created_at"`
	WithdrawnAt          pgtype.Timestamptz `json:"withdrawn_at"`
	WithdrawnReason      pgtype.Text        `json:"withdrawn_reason"`
	CreatedByAdminUserID pgtype.UUID        `json:"created_by_admin_user_id"`
}

func (q *Queries) GetQuestion(ctx context.Context, id pgtype.UUID) (GetQuestionRow, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i GetQuestionRow
	err := row.Scan(
		&i.ID,
		&i.CurrentRevisionID,
		&i.IsActive,
		&i.CreatedAt,
		&i.RevisionID,
		&i.Text,
		&i.Category,
		&i.RelationshipFit,
		&i.ModeFit,
		&i.Intensity,
		&i.RevisionNumber,
		&i.RevisionCreatedAt,
		&i.WithdrawnAt,
		&i.WithdrawnReason,
		&i.CreatedByAdminUserID,
	)
	return i, err
}

const getQuestionRevision = `-- name: GetQuestionRevision :one
SELECT id, question_id, text, category, relationship_fit, mode_fit, intensity,
       revision_number, created_by_admin_user_id, withdrawn_at, withdrawn_reason,
       withdrawn_by_admin_user_id, created_at
FROM question_revision WHERE id = $1 AND question_id = $2
`

type GetQuestionRevisionParams struct {
	ID         pgtype.UUID `json:"id"`
	QuestionID pgtype.UUID `json:"question_id"`
}

func (q *Queries) GetQuestionRevision(ctx context.Context, arg GetQuestionRevisionParams) (QuestionRevision, error) {
	row := q.db.QueryRow(ctx, getQuestionRevision, arg.ID, arg.QuestionID)
	var i QuestionRevision
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.Category,
		&i.RelationshipFit,
		&i.ModeFit,
		&i.Intensity,
		&i.RevisionNumber,
		&i.CreatedByAdminUserID,
		&i.WithdrawnAt,
		&i.WithdrawnReason,
		&i.WithdrawnByAdminUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listQuestionRevisions = `-- name: ListQuestionRevisions :many
SELECT id, question_id, text, category, relationship_fit, mode_fit, intensity,
       revision_number, created_by_admin_user_id, withdrawn_at, withdrawn_reason,
       withdrawn_by_admin_user_id, created_at
FROM question_revision WHERE question_id = $1 ORDER BY revision_number DESC
`

func (q *Queries) ListQuestionRevisions(ctx context.Context, questionID pgtype.UUID) ([]QuestionRevision, error) {
	rows, err := q.db.Query(ctx, listQuestionRevisions, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionRevision
	for rows.Next() {
		var i QuestionRevision
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.Category,
			&i.RelationshipFit,
			&i.ModeFit,
			&i.Intensity,
			&i.RevisionNumber,
			&i.CreatedByAdminUserID,
			&i.WithdrawnAt,
			&i.WithdrawnReason,
			&i.WithdrawnByAdminUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT q.id, q.current_revision_id, q.is_active, q.created_at,
       r.text, r.category, r.relationship_fit, r.mode_fit, r.intensity,
       r.revision_number, r.created_at AS revision_created_at, r.withdrawn_at
FROM question q JOIN question_revision r ON r.id = q.current_revision_id
WHERE ($1::text = '' OR r.text ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR r.category = $2)
  AND ($3::text = '' OR r.intensity = $3)
  AND ($4::text = '' OR r.relationship_fit = $4)
  AND ($5::text = '' OR r.mode_fit = $5)
ORDER BY q.created_at DESC, q.id LIMIT $6 OFFSET $7
`

type ListQuestionsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 string `json:"column_5"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListQuestionsRow struct {
	ID                pgtype.UUID        `json:"id"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Text              string             `json:"text"`
	Category          string             `json:"category"`
	RelationshipFit   string             `json:"relationship_fit"`
	ModeFit           string             `json:"mode_fit"`
	Intensity         string             `json:"intensity"`
	RevisionNumber    int32              `json:"revision_number"`
	RevisionCreatedAt pgtype.Timestamptz `json:"revision_created_at"`
	WithdrawnAt       pgtype.Timestamptz `json:"withdrawn_at"`
}

func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]ListQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listQuestions,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsRow
	for rows.Next() {
		var i ListQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CurrentRevisionID,
			&i.IsActive,
			&i.CreatedAt,
			&i.Text,
			&i.Category,
			&i.RelationshipFit,
			&i.ModeFit,
			&i.Intensity,
			&i.RevisionNumber,
			&i.RevisionCreatedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockQuestion = `-- name: LockQuestion :one
SELECT id, current_revision_id, is_active, created_at FROM question WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockQuestion(ctx context.Context, id pgtype.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, lockQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CurrentRevisionID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const nextQuestionRevisionNumber = `-- name: NextQuestionRevisionNumber :one
SELECT COALESCE(MAX(revision_number), 0) + 1 AS next_revision_number FROM question_revision WHERE question_id = $1
`

func (q *Queries) NextQuestionRevisionNumber(ctx context.Context, questionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextQuestionRevisionNumber, questionID)
	var next_revision_number int32
	err := row.Scan(&next_revision_number)
	return next_revision_number, err
}

const setCurrentQuestionRevision = `-- name: SetCurrentQuestionRevision :exec
UPDATE question SET current_revision_id = $2 WHERE id = $1
`

type SetCurrentQuestionRevisionParams struct {
	ID                pgtype.UUID `json:"id"`
	CurrentRevisionID pgtype.UUID `json:"current_revision_id"`
}

func (q *Queries) SetCurrentQuestionRevision(ctx context.Context, arg SetCurrentQuestionRevisionParams) error {
	_, err := q.db.Exec(ctx, setCurrentQuestionRevision, arg.ID, arg.CurrentRevisionID)
	return err
}

const setQuestionActivity = `-- name: SetQuestionActivity :exec
UPDATE question SET is_active = $2 WHERE id = $1
`

type SetQuestionActivityParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) SetQuestionActivity(ctx context.Context, arg SetQuestionActivityParams) error {
	_, err := q.db.Exec(ctx, setQuestionActivity, arg.ID, arg.IsActive)
	return err
}

const withdrawQuestionRevision = `-- name: WithdrawQuestionRevision :exec
UPDATE question_revision SET withdrawn_at = COALESCE(withdrawn_at, now()), withdrawn_reason = COALESCE(withdrawn_reason, $3), withdrawn_by_admin_user_id = COALESCE(withdrawn_by_admin_user_id, $4) WHERE id = $1 AND question_id = $2
`

type WithdrawQuestionRevisionParams struct {
	ID                     pgtype.UUID `json:"id"`
	QuestionID             pgtype.UUID `json:"question_id"`
	WithdrawnReason        pgtype.Text `json:"withdrawn_reason"`
	WithdrawnByAdminUserID pgtype.UUID `json:"withdrawn_by_admin_user_id"`
}

func (q *Queries) WithdrawQuestionRevision(ctx context.Context, arg WithdrawQuestionRevisionParams) error {
	_, err := q.db.Exec(ctx, withdrawQuestionRevision,
		arg.ID,
		arg.QuestionID,
		arg.WithdrawnReason,
		arg.WithdrawnByAdminUserID,
	)
	return err
}
