// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_helpers.sql

package sqlc

import (
	"context"
)

const currentDatabase = `-- name: CurrentDatabase :one

SELECT current_database()::text
`

// Infrastructure-only query used by the test-database guard and transaction
// smoke tests. Domain query files belong to their owning tickets.
func (q *Queries) CurrentDatabase(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, currentDatabase)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getLocalTestValue = `-- name: GetLocalTestValue :one
SELECT COALESCE(current_setting('closer.go02_test_value', true), '')::text
`

func (q *Queries) GetLocalTestValue(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getLocalTestValue)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const setLocalTestValue = `-- name: SetLocalTestValue :one
SELECT set_config('closer.go02_test_value', $1::text, true)::text
`

func (q *Queries) SetLocalTestValue(ctx context.Context, value string) (string, error) {
	row := q.db.QueryRow(ctx, setLocalTestValue, value)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
