// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: together.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closePreclaimTogetherSessions = `-- name: ClosePreclaimTogetherSessions :exec
UPDATE together_session SET ended_at = COALESCE(ended_at, clock_timestamp())
WHERE pair_id = $1 AND membership_era_id IS NULL AND ended_at IS NULL
`

func (q *Queries) ClosePreclaimTogetherSessions(ctx context.Context, pairID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, closePreclaimTogetherSessions, pairID)
	return err
}

const createTogetherSession = `-- name: CreateTogetherSession :one
INSERT INTO together_session (pair_id, membership_era_id, category, started_by_participant_id, start_request_id, selection_seed)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, pair_id, membership_era_id, category, started_by_participant_id, start_request_id, selection_seed, started_at, ended_at
`

type CreateTogetherSessionParams struct {
	PairID                 pgtype.UUID `json:"pair_id"`
	MembershipEraID        pgtype.UUID `json:"membership_era_id"`
	Category               string      `json:"category"`
	StartedByParticipantID pgtype.UUID `json:"started_by_participant_id"`
	StartRequestID         pgtype.UUID `json:"start_request_id"`
	SelectionSeed          string      `json:"selection_seed"`
}

func (q *Queries) CreateTogetherSession(ctx context.Context, arg CreateTogetherSessionParams) (TogetherSession, error) {
	row := q.db.QueryRow(ctx, createTogetherSession,
		arg.PairID,
		arg.MembershipEraID,
		arg.Category,
		arg.StartedByParticipantID,
		arg.StartRequestID,
		arg.SelectionSeed,
	)
	var i TogetherSession
	err := row.Scan(
		&i.ID,
		&i.PairID,
		&i.MembershipEraID,
		&i.Category,
		&i.StartedByParticipantID,
		&i.StartRequestID,
		&i.SelectionSeed,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createTogetherSessionQuestion = `-- name: CreateTogetherSessionQuestion :one
INSERT INTO together_session_question (session_id, question_id, question_revision_id, position)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, question_id, question_revision_id, position, shown_at, liked_at, skipped_at, advanced_at, advance_request_id
`

type CreateTogetherSessionQuestionParams struct {
	SessionID          pgtype.UUID `json:"session_id"`
	QuestionID         pgtype.UUID `json:"question_id"`
	QuestionRevisionID pgtype.UUID `json:"question_revision_id"`
	Position           int32       `json:"position"`
}

func (q *Queries) CreateTogetherSessionQuestion(ctx context.Context, arg CreateTogetherSessionQuestionParams) (TogetherSessionQuestion, error) {
	row := q.db.QueryRow(ctx, createTogetherSessionQuestion,
		arg.SessionID,
		arg.QuestionID,
		arg.QuestionRevisionID,
		arg.Position,
	)
	var i TogetherSessionQuestion
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.QuestionID,
		&i.QuestionRevisionID,
		&i.Position,
		&i.ShownAt,
		&i.LikedAt,
		&i.SkippedAt,
		&i.AdvancedAt,
		&i.AdvanceRequestID,
	)
	return i, err
}
